automation:
  - alias: 3D Printer - Notify Me When Print Has Finished
    id: 3d_printer_notify_me_when_print_has_finished
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: "on"
        to: "off"
    variables:
      notification_title: 3D Print Finished
      notification_message: Your 3D print has completed.
    action:
      - alias: "Only announce between 9am and 9pm"
        wait_template: "{{ now().hour < 21 and now().hour >= 9 }}"
      - service: script.chatgpt_reword_message
        data:
          prompt: "{{ notification_message }}"
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          title: "{{ notification_title }}"
          message: "{{ chatgpt_response.text }}"
          data:
            group: "3D Printer"
            image: /api/camera_proxy/camera.ender_3_s1
            notification_icon: "mdi:printer-3d"
      - condition: state
        entity_id: media_player.kitchen_google_home_hub
        state: "off" # Only use text-to-speech on Google Home Hub if it's not already in use, so it doesn't stop any music from playing
      - service: script.custom_speak_notification 
        data:
          message_to_speak: "{{ chatgpt_response.text }}"
          media_player: media_player.all_rooms
