script:
  #Warm the master bedroom for 60 minutes
  aircon_warm_master:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 22
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: heat
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_on
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_off
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    - delay:
        seconds: 10
    - data:
        entity_id: input_number.aircon_countdown_timer
        value: 60
      service: input_number.set_value
    alias: Aircon Warm Master
    
  #Run the fan in the master bedroom for 60 minutes
  aircon_fan_master:
    sequence:
    - data:
        entity_id: input_select.aircon_run_mode
        option: vent
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_on
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_off
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    - delay:
        seconds: 10
    - data:
        entity_id: input_number.aircon_countdown_timer
        value: 60
      service: input_number.set_value
    alias: Aircon Fan Master
    
  #Run the aircon in the central living area
  aircon_cool_central_living:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 21
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: cool
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_on
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_off
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Aircon Cool Central Living

  #Run the aircon in the theatre room
  aircon_cool_theatre:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 23
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: cool
      service: input_select.select_option
    - data:
        entity_id: switch.aircon_zone_bed23
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_living
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_master
      service: switch.turn_off
    - data:
        entity_id: switch.aircon_zone_theatre
      service: switch.turn_on
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Aircon Cool Theatre

  #Run the aircon in cool mode
  aircon_cool:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 20
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: cool
      service: input_select.select_option
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Aircon On
    
  #Run the aircon in heat mode
  aircon_heat:
    sequence:
    - data:
        entity_id: input_number.aircon_temperature
        value: 24
      service: input_number.set_value
    - delay:
        seconds: 1
    - data:
        entity_id: input_select.aircon_run_mode
        option: heat
      service: input_select.select_option
    - delay:
        seconds: 1
    - data:
        entity_id: switch.aircon_on_off
      service: switch.turn_on
    alias: Heater On

  #Save the current aircon state, blast aircon for 10 min, then restore state.
  aircon_blast_cold_for_ten_minutes:
    sequence:
      - service: scene.create
        data:
          scene_id: aircon_saved_state
          snapshot_entities:
            - switch.aircon_on_off
            - input_select.aircon_run_mode
            - input_number.aircon_temperature
      - service: input_select.select_option
        data:
          entity_id: input_select.aircon_run_mode
          option: "cool"
      - delay:
          seconds: 1
      - service: input_number.set_value
        data:
          entity_id: input_number.aircon_temperature
          value: 21
      - delay:
          seconds: 1
      - service: switch.turn_on
        data:
          entity_id: switch.aircon_on_off
      - delay:
          minutes: 10
      - service: scene.turn_on
        data:
          entity_id: scene.aircon_saved_state
      - delay:
          seconds: 1
      - service: scene.turn_on #dodgy workaround to avoid sending too many requests to the AC controller at once.
        data:
          entity_id: scene.aircon_saved_state
          
automation:
  - alias: Temperature - Morning Warmth
    trigger:
      - platform: time
        at: '06:00:00'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: numeric_state
        entity_id: sensor.master_bedroom_temperature
        below: '15'
        value_template: '{{ state.attributes.temperature }}'
    action:
      - service: script.aircon_warm_master

  - alias: Temperature - Solar Cooling
    trigger:
      platform: time_pattern
      minutes: "/1" #This will match every 1 minutes
    condition:
      - condition: template
        value_template: '{{ (states.sensor.living_room_temperature.state | float) > 25.0 }}' #if the inside temperature is > 25 degrees  
      - condition: template
        value_template: '{{ (states.sensor.sems_output_power.state | float) > 2000.0 }}' #if the solar panels are running well
      - condition: state
        entity_id: 'alarm_control_panel.alarm_com'
        state: 'armed_away' #nobody is home
      - condition: state
        entity_id: 'switch.aircon_on_off'
        state: 'off' #don't run the script if the aircon is already on, as it will restart the countdown timer
    action:
      - service: script.aircon_cool_central_living #run the aircon in the central living area
      - delay: #wait until it's up and running
          seconds: 30 
      - service: input_number.set_value #stop the aircon after 15 minutes
        data_template: 
          entity_id: input_number.aircon_countdown_timer
          value: 15

  - alias: Temperature - Master Bed Button Trigger - Fan
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_bed_switch_1
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_bed_switch_2
          event: 1002
    condition:
      - condition: template
        value_template: '{{ (states.sensor.master_bedroom_temperature.state | float) > 22.0 }}' 
      - condition: state
        entity_id: 'switch.aircon_on_off'
        state: 'off' #aircon is currently off
    action:
      - service: script.aircon_fan_master 

  - alias: Temperature - Master Bed Button Trigger - Warm
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_bed_switch_1
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_bed_switch_2
          event: 1002
    condition:
      - condition: template
        value_template: '{{ (states.sensor.master_bedroom_temperature.state | float) <= 22.0 }}' 
      - condition: state
        entity_id: 'switch.aircon_on_off'
        state: 'off' #aircon is currently off
    action:
      - service: script.aircon_warm_master 

  - alias: Temperature - Master Bed Button Trigger - Off
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_bed_switch_1
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_bed_switch_2
          event: 1002
    condition:
      - condition: state
        entity_id: 'switch.aircon_on_off'
        state: 'on' #aircon is currently on
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.aircon_on_off
