# NOTE: Aircon countdown timer is still controlled using the older IP-based approach as the 
#       new integration cannot yet accept a template or variable in place of the number
rest_command:
  aircon_control:
    url: "http://192.168.1.106:2025/setAircon?json={{ command }}"
    method: "GET"

input_number:
  aircon_countdown_timer:
    name: Aircon Countdown Timer
    initial: 0
    min: 0
    max: 300
    step: 15

automation:
  - alias: Aircon Control - Adjust Countdown Timer From Slider
    trigger:
      platform: state
      entity_id: input_number.aircon_countdown_timer
    action:
      - service: rest_command.aircon_control
        data_template:
          command: '{"ac1":{"info":{"countDownToOff":{{ states.input_number.aircon_countdown_timer.state | int }}}}}'
  - alias: Aircon Control - Adjust Countdown Timer From Sensor
    trigger:
      platform: state
      entity_id: sensor.ac_time_to_off
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.aircon_countdown_timer
          value: "{{ states.sensor.ac_time_to_off.state }}"

switch:
  - platform: template
    switches:
      aircon_zone_living: #zone z01
        value_template: "{{ is_state('cover.living', 'open') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.living
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.living

      aircon_zone_theatre: #zone z02
        value_template: "{{ is_state('cover.theatre', 'open') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.theatre
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.theatre

      aircon_zone_master: #zone z03
        value_template: "{{ is_state('cover.master_bed', 'open') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.master_bed
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.master_bed

      aircon_zone_bed23: #zone z04
        value_template: "{{ is_state('cover.bed_2_3', 'open') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.bed_2_3
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.bed_2_3

group:
  aircon_vents:
    name: Aircon Vents
    entities:
      - switch.aircon_zone_bed23
      - switch.aircon_zone_living
      - switch.aircon_zone_master
      - switch.aircon_zone_theatre
