alarm_control_panel:
  platform: alarmdotcom
  scan_interval: 10
  username: !secret alarmdotcom_username
  password: !secret alarmdotcom_password

automation:
  - alias: Alarm System - Notify If Alarm Not Set When Nobody Is Home
    id: alarm_system_notify_if_alarm_not_set_when_nobody_is_home
    trigger:
      - platform: zone
        entity_id: person.laura
        zone: zone.home
        event: leave
      - platform: zone
        entity_id: person.michael
        zone: zone.home
        event: leave
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ not is_state('person.michael','home') }}"
        - condition: template
          value_template: "{{ not is_state('person.laura','home') }}"
        - condition: state
          entity_id: alarm_control_panel.alarm_com
          state: 'disarmed'
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: The house alarm was not set and nobody is home.

  #If the alarm was in armed_home mode for more than 5 minutes and then it stays armed for more than
  #one minute after coming home, remind us to disarm the alarm
  - alias: Alarm System - Notify If Alarm Not Disarmed When Coming Home
    id: alarm_system_notify_if_alarm_not_disarmed_when_coming_home
    mode: single
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.garage_door_internal
        to: 'on' #open
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: 'armed_home' #armed_home mode is silent when coming home, hence the need for this automation
        for:
          minutes: 5
    action:
      - delay:
          minutes: 1
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: 'armed_home'
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: Don't forget to disarm the alarm!
          title: Alarm is armed!
          data:
            group: Disarm Alarm
            color: 'red'
            ttl: 0
            priority: high
      - service: notify.mobile_app_lauras_iphone
        data:
          message: Don't forget to disarm the alarm!
      - service: tts.google_translate_say
        data:
          entity_id: media_player.kitchen_google_home_hub
          message: Don't forget to disarm the alarm!
          
  - alias: Alarm System - Turn Off House When Alarm Is Set
    id: alarm_system_turn_off_house_when_alarm_is_set
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_com
        from: 'disarmed'
        to: 'armed_away'
      - platform: state
        entity_id: alarm_control_panel.alarm_com
        from: 'disarmed'
        to: 'armed_home'
    action:
      - service: script.turn_off_whole_house
        data: 
          excluded_lights: "['light.garage', 'light.garage_light', 'light.front_porch_light']" #Leave these lights on if they're already on
          turn_off_aircon: true
        
  - alias: Alarm System - Alert If Doors Left Open
    id: alarm_system_alert_if_doors_left_open
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm_com
      to: 'armed_away'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.back_door_glass
          state: 'on'
        - condition: state
          entity_id: binary_sensor.laundry_door
          state: 'on'
        - condition: state
          entity_id: bindary_sensor.front_door
          state: 'on'
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: A door was left open when the house alarm was set.
      - service: notify.mobile_app_lauras_iphone
        data:
          message: A door was left open when the house alarm was set.

sensor:
  - platform: template
    scan_interval: 10
    sensors:
      alarmdotcom_front_door: #front door open/closed sensor
        friendly_name: "Front Door"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Front Door is Open', ignorecase=True) %}
            Open
          {% else %}
            Closed
          {% endif %}
      alarmdotcom_motion_sensor_living: #living room motion sensor
        friendly_name: "Living Room Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Living Sensor is Activated', ignorecase=True) %}
            Active
          {% else %}
            Inactive
          {% endif %}
      alarmdotcom_motion_sensor_master_bedroom: #master bedroom motion sensor
        friendly_name: "Master Bedroom Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Master Bedroom Sensor is Activated', ignorecase=True) %}
            Active
          {% else %}
            Inactive
          {% endif %}
      alarmdotcom_motion_sensor_entry_hall: #entry hall motion sensor
        friendly_name: "Entry Hall Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Entry Sensor is Open', ignorecase=True) %}
            Active
          {% else %}
            Inactive
          {% endif %}
