alarm_control_panel:
  platform: alarmdotcomajax
  scan_interval: 10
  username: !secret alarmdotcom_username
  password: !secret alarmdotcom_password

automation:
  # - alias: Alarm System - Notify If Alarm Not Set When Nobody Is Home
  #   trigger:
  #     - platform: zone
  #       entity_id: device_tracker.lauras_iphone
  #       zone: zone.home
  #       event: leave
  #     - platform: zone
  #       entity_id: device_tracker.michael_michaelgalaxys10_2
  #       zone: zone.home
  #       event: leave
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: template
  #         value_template: "{{ not is_state('device_tracker.lauras_iphone','home') }}"
  #       - condition: template
  #         value_template: "{{ not is_state('device_tracker.michael_michaelgalaxys10_2','home') }}"
  #       - condition: state
  #         entity_id: alarm_control_panel.alarm_com
  #         state: 'disarmed'
  #   action:
  #     - service: notify.mobile_app_michael_s_galaxy_s10 #notify Michael
  #       data:
  #         message: The house alarm was not set.
          
  - alias: Alarm System - Turn Off House When Alarm Is Set
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm_com
      from: 'disarmed'
      to: 'armed_away'
    action:
      - service: script.turn_off_whole_house
        data: 
          excluded_lights: "['light.garage', 'light.garage_light', 'light.front_porch_light']" #Leave these lights on if they're already on
        
  - alias: Alarm System - Alert If Doors Left Open
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm_com
      to: 'armed_away'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.back_door_glass
          state: 'on'
        - condition: state
          entity_id: binary_sensor.laundry_door
          state: 'on'
        - condition: state
          entity_id: bindary_sensor.front_door
          state: 'on'
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: A door was left open when the house alarm was set.
      - service: notify.mobile_app_lauras_iphone
        data:
          message: A door was left open when the house alarm was set.

sensor:
  - platform: template
    scan_interval: 10
    sensors:
      alarmdotcom_front_door: #front door open/closed sensor
        friendly_name: "Front Door"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Front Door is Open', ignorecase=TRUE) %}
            Open
          {% else %}
            Closed
          {% endif %}
      alarmdotcom_motion_sensor_living: #living room motion sensor
        friendly_name: "Living Room Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Living Sensor is Activated', ignorecase=TRUE) %}
            Active
          {% else %}
            Inactive
          {% endif %}
      alarmdotcom_motion_sensor_master_bedroom: #master bedroom motion sensor
        friendly_name: "Master Bedroom Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Master Bedroom Sensor is Activated', ignorecase=TRUE) %}
            Active
          {% else %}
            Inactive
          {% endif %}
      alarmdotcom_motion_sensor_entry_hall: #entry hall motion sensor
        friendly_name: "Entry Hall Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Entry Sensor is Open', ignorecase=TRUE) %}
            Active
          {% else %}
            Inactive
          {% endif %}
