automation:
  - alias: Board Game Music - Handle Tag Scan
    id: handle_tag_scan
    mode: single
    # Hide warnings when triggered while in delay.
    max_exceeded: silent
    variables:
      tags:
        fa9383b4-7665-44d3-8389-f4d710bbed7f:
          playlist_name: "adventure"
        35d1beca-0ca0-413f-8c37-ea32807d810e:
          playlist_name: "ancient"
        1e722b56-bd54-4f37-81fb-4b08bac42158:
          playlist_name: "battle"
        c5893482-5245-4db0-9048-89624d502af4:
          playlist_name: "cafe"
        12b970f1-e1b3-4231-91b8-f949e5a57bbc:
          playlist_name: "casino"
        3558fbf6-ffd0-4b96-afb3-467bb42261d2:
          playlist_name: "china"
        599fb41a-cba2-4757-b637-2a112d58911f:
          playlist_name: "cities"
        898a565e-a2df-4bba-aad9-2ebf5014b7f9:
          playlist_name: "detective"
        c485bda5-cf0f-47b4-9fa8-a04180811d69:
          playlist_name: "dungeon"
        76f7e283-2ccb-433b-8b4d-f82d20bdd955:
          playlist_name: "egyptian"
        ddc89527-8b98-4f31-a87e-1eb74de9ca4c:
          playlist_name: "french"
        98ddb5d0-4fc0-4543-a57d-cc9efebf6393:
          playlist_name: "gangster"
        1036cd92-4aef-4e71-a7c1-73e7882fe4f4:
          playlist_name: "gloomhaven"
        48695443-cc56-4b6f-a931-52dd62816307:
          playlist_name: "gloomhaven"
        6ad75fa6-cd9e-456f-a1f5-42469ce65f10:
          playlist_name: "horror"
        7006a1c6-296b-48e1-9688-f05c2ce94db4:
          playlist_name: "india"
        16951460-6e0a-43ba-b269-269e017a0842:
          playlist_name: "japan"
        ece9aecf-83a2-4d49-90d3-2baeaa740067:
          playlist_name: "magic"
        859be98a-d662-48bc-ba51-3001aa8f26b4:
          playlist_name: "medieval_town"
        49ca3e03-e2f7-4651-a410-84405b669d3e:
          playlist_name: "meditation"
        7f6f84f4-482f-40cb-abac-a579078472ac:
          playlist_name: "mythical"
        a587a967-b4d4-4b04-8752-54330efd99ab:
          playlist_name: "pirates"
        a5002884-c6c1-4e92-b346-77b08e8ce712:
          playlist_name: "renaissance"
        48cf9936-1291-4b18-a474-19af232796b3:
          playlist_name: "space"
        fc91721f-e5c5-4101-ad51-565b00dd73f4:
          playlist_name: "spy"
        dda894d9-b946-4efc-bf07-f43f0a11588a:
          playlist_name: "water"
        bbf95209-9cce-45f9-92bd-f3ec07b9d289:
          playlist_name: "western"
    trigger:
      platform: event
      event_type: tag_scanned
    condition:
      # Test that we support this device and tag
      - "{{ trigger.event.data.tag_id in tags }}"
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: The {{ tags[trigger.event.data.tag_id].playlist_name }} playlist will be played.
          data:
            timeout: 10
            channel: BoardGameAlerts
            importance: high
      - service: script.play_board_game_music_playlist_in_kitchen
        data: 
          playlist_name: '{{ tags[trigger.event.data.tag_id].playlist_name }}'

script:
  play_board_game_music_playlist_in_kitchen:
    alias: Board Game Music - Play Playlist In Kitchen
    fields: 
      playlist_name: 
        description: 'The playlist which should be played'
        example: 'pirates'
    variables:
      playlists:
        adventure: 
          playlist_id: "PLavpVzwAAU9bWWSA9tN7EtDqFGRhF6Dva"
        ancient: 
          playlist_id: "PLavpVzwAAU9a5DrqFLhWEcBkoIrPH0aGz"
        battle: 
          playlist_id: "PLavpVzwAAU9Y8EJESUQzeIB-XKAfLqfze"
        cafe: 
          playlist_id: "PLavpVzwAAU9bi-3jXB2Hs9RNkZZWUxBOG"
        casino: 
          playlist_id: "PLavpVzwAAU9ZbA6XJR0oT86FLWGCyDCq5"
        china: 
          playlist_id: "PLavpVzwAAU9bHfLOMampDIe_XhYP08bdZ"
        cities: 
          playlist_id: "PLavpVzwAAU9biE9BBwvrpnVFNlXSfiM9h"
        detective: 
          playlist_id: "PLavpVzwAAU9ZAcIzK_cZGywhaWNC70en6"
        dungeon: 
          playlist_id: "PLavpVzwAAU9bi9hKI0po6DE3yibLcIHRk"
        egyptian: 
          playlist_id: "PLavpVzwAAU9YdQ_y4gkwtcgj7ReWa5wsy"
        french: 
          playlist_id: "PLavpVzwAAU9aUT4bO4IjhRXsIw0ICuM6B"
        gangster: 
          playlist_id: "PLavpVzwAAU9bK13tDSN7pogWWsu25K6vA"
        gloomhaven: 
          playlist_id: "PLavpVzwAAU9ZiQn69q55xm_Vzj9ZiA-M7"
        horror: 
          playlist_id: "PLavpVzwAAU9aR5V1A2lErsNLtqEorawx-"
        india: 
          playlist_id: "PLavpVzwAAU9aY5DO92CiaA8qR1DG6UvWP"
        japan: 
          playlist_id: "PLavpVzwAAU9Zv5nUaUNKBTPmIwLJ965Q7"
        magic: 
          playlist_id: "PLavpVzwAAU9aLuX06cbMK_EvVjlN0Gjvc"
        medieval_town: 
          playlist_id: "PLavpVzwAAU9b4G2MeVBZ5o35vJHT-zD3W"
        meditation: 
          playlist_id: "PLavpVzwAAU9axEP9wn3OfRSwCtewAUCfT"
        mythical: 
          playlist_id: "PLavpVzwAAU9aTzc6mxdSgWFqkB3_39MZ6"
        pirates: 
          playlist_id: "PLavpVzwAAU9ZPwauocZ6_5xPJ5LLdXedV"
        renaissance: 
          playlist_id: "PLavpVzwAAU9YBF1M0T8txK8p1Suyj6nms"
        space: 
          playlist_id: "PLavpVzwAAU9Ywsbz7_I1A5v3Qfpdx43bC"
        spy: 
          playlist_id: "PLavpVzwAAU9Z4Isj-XdXkCG6AQ9GjXr1S"
        water: 
          playlist_id: "PLavpVzwAAU9aFuWrnrI8E458ILtfUHrif"
        western: 
          playlist_id: "PLavpVzwAAU9bsH4JeaXcLxZqGaPM2bjwh"
    sequence:
      - service: script.youtube_randomize_playlist
        data:
          media_entity: media_player.kitchen_google_home_hub
          playlist_id: "{{ playlists[playlist_name].playlist_id }}"
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_google_home_hub
          volume_level: 0.5