# sensor:
#   - platform: mqtt
#     name: "Mazda CX-5"
#     state_topic: "obd/sensor/mazda/state"
#     device:
#       name: "Michael's Mazda CX-5"
#       manufacturer: "Mazda"
#       model: "2015 CX-5"
#       suggested_area: "garage"
#     icon: mdi:car

template:
  - binary_sensor:
      - name: "Michael Phone Is Docked In The Car"
        state: "{{states('binary_sensor.pixel_8_pro_is_charging') and 'FC:35:E6:53:2C:C9 (Mazda)' in state_attr('sensor.pixel_8_pro_bluetooth_connection', 'connected_paired_devices')}}"

  - sensor:
      - name: "Lowest Fuel Price"
        unit_of_measurement: "c"
        state: >
          {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
          {{ cheapest['price'] }}
      - name: "Local Fuel Price"
        unit_of_measurement: "c"
        state: >
          {{ 
              state_attr('sensor.rss_fuel_watch_ulp','entries')
              | selectattr("trading-name","equalto", "Ampol Foodary Cockburn Central") 
              | map(attribute='price') 
              | first() 
          }}
        attributes:
          premium: >
            {{ 
                (
                  ( states('sensor.local_fuel_price') | float | round(1, 'common') )
                - ( states('sensor.lowest_fuel_price') | float | round(1, 'common') )
                ) | round(1)
            }}
      - name: "Local Fuel Premium"
        unit_of_measurement: "c"
        state: >
          {{ 
              ( states('sensor.local_fuel_price') | float | round(1, 'common') )
            - ( states('sensor.lowest_fuel_price') | float | round(1, 'common') )
          }}
      - name: "Cheapest Fuel Location"
        icon: mdi:gas-station
        state: >
          {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
          {{ cheapest["title"] }} - {{ cheapest["address"] }}
      - name: "Local Fuel Location"
        icon: mdi:gas-station
        state: >
          {% set local = (state_attr('sensor.rss_fuel_watch_ulp','entries') | selectattr("trading-name","equalto", "Ampol Foodary Cockburn Central") | first )  %}
          {{ local["title"] }} - {{ local["address"] }}
      - name: "Cheapest Fuel Address For Navigation"
        icon: mdi:gas-station
        state: >
          {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
          {{ (cheapest["address"] + " " + cheapest["location"]) | replace(" ", "+") }}

  - binary_sensor:
      - name: Cheapest Fuel Station
        state: true
        device_class: "presence"
        icon: mdi:gas-station
        attributes:
          latitude: >
            {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
            {{ cheapest['latitude'] }}
          longitude: >
            {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
            {{ cheapest['longitude'] }}

sensor:
  - platform: feedparser
    name: RSS Fuel Watch ULP
    feed_url: "http://www.fuelwatch.wa.gov.au/fuelwatch/fuelWatchRSS?Product=1&Suburb=Cockburn+Central"
    show_topn: 10
    date_format: "%a, %b %d %I:%M %p"
    inclusions:
      - title
      - description
      - price
      - link
      - item
      - brand
      - date
      - trading-name
      - location
      - address
      - latitude
      - longitude
    exclusions:
      - language

  - platform: feedparser
    name: RSS Fuel Watch ULP Tomorrow
    feed_url: "http://www.fuelwatch.wa.gov.au/fuelwatch/fuelWatchRSS?Product=1&Suburb=Cockburn+Central&Day=Tomorrow"
    show_topn: 10
    date_format: "%a, %b %d %I:%M %p"
    inclusions:
      - title
      - description
      - price
      - link
      - item
      - brand
      - date
      - trading-name
      - location
      - address
    exclusions:
      - language

automation:
  - alias: Driving - Launch Google Maps When Phone Connects To Car
    trigger:
      - platform: state
        entity_id: binary_sensor.michael_phone_is_docked_in_the_car
        from: "off"
        to: "on"
    action:
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "command_launch_app"
          data:
            package_name: "com.google.android.apps.maps"

script:
  navigate_to_cheapest_fuel_station:
    icon: mdi:navigation
    alias: "Driving - Navigate To Cheapest Fuel Station"
    sequence:
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "command_activity"
          data:
            intent_package_name: "com.google.android.apps.maps"
            intent_action: "android.intent.action.VIEW"
            intent_uri: >
              geo:0,0?q={{ states('sensor.cheapest_fuel_address_for_navigation') }}
