# sensor:
#   - platform: mqtt
#     name: "Mazda CX-5"
#     state_topic: "obd/sensor/mazda/state"
#     device:
#       name: "Michael's Mazda CX-5"
#       manufacturer: "Mazda"
#       model: "2015 CX-5"
#       suggested_area: "garage"
#     icon: mdi:car

template:
  - sensor:
      - name: "Lowest Fuel Price"
        unit_of_measurement: "c"
        state: >
          {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
          {{ cheapest['price'] }}
      - name: "Local Fuel Price"
        unit_of_measurement: "c"
        state: >
          {{ 
              state_attr('sensor.rss_fuel_watch_ulp','entries')
              | selectattr("trading-name","equalto", "Ampol Foodary Cockburn Central") 
              | map(attribute='price') 
              | first() 
          }}
        attributes:
          premium: >
            {{ 
                ( states('sensor.local_fuel_price') | float | round(1, 'common') )
              - ( states('sensor.lowest_fuel_price') | float | round(1, 'common') )
            }}
      - name: "Local Fuel Premium"
        unit_of_measurement: "c"
        state: >
            {{ 
                ( states('sensor.local_fuel_price') | float | round(1, 'common') )
              - ( states('sensor.lowest_fuel_price') | float | round(1, 'common') )
            }}

  - binary_sensor:          
      - name: Cheapest Fuel Station
        state: true
        device_class: "presence"
        icon: mdi:gas-station
        attributes:
          latitude: >
            {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
            {{ cheapest['latitude'] }}
          longitude: >
            {% set cheapest = (state_attr('sensor.rss_fuel_watch_ulp','entries') | first) %}
            {{ cheapest['longitude'] }}

sensor:
  - platform: feedparser
    name: RSS Fuel Watch ULP
    feed_url: 'http://www.fuelwatch.wa.gov.au/fuelwatch/fuelWatchRSS?Product=1&Suburb=Cockburn+Central'
    show_topn: 10
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - description
      - price
      - link
      - item
      - brand
      - date
      - trading-name
      - location
      - address
      - latitude
      - longitude
    exclusions:
      - language

  - platform: feedparser
    name: RSS Fuel Watch ULP Tomorrow
    feed_url: 'http://www.fuelwatch.wa.gov.au/fuelwatch/fuelWatchRSS?Product=1&Suburb=Cockburn+Central&Day=Tomorrow'
    show_topn: 10
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - description
      - price
      - link
      - item
      - brand
      - date
      - trading-name
      - location
      - address
    exclusions:
      - language
