automation:
    #if coffee machine left open, send a push notification.
    - alias: Coffee - Notify If Coffee Machine Closed for 5 Minutes
      trigger:
        platform: time_pattern
        minutes: '/5' #run every 5 minutes
      condition:
        condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.coffee_machine
            state: 'off'
            for:
              minutes: 4
      action:
        - service: notify.pushbullet
          data:
            message: The coffee machine was left closed.
        - service: notify.mobile_app_lauras_iphone
          data:
            message: The coffee machine was left closed.
        - data:
            entity_id: media_player.kitchen_google_home_hub
            message: The coffee machine was left closed.
          service: tts.google_translate_say