template:
  - binary_sensor:
      - name: "Michael Phone Is Docked In The Car"
        state: "{{states('binary_sensor.michael_s_galaxy_s10_is_charging') and 'FC:35:E6:53:2C:C9 (Mazda)' in state_attr('sensor.michael_s_galaxy_s10_bluetooth_connection', 'connected_paired_devices')}}"
        
automation:
  - alias: Driving - Launch Google Maps When Phone Connects To Car
    trigger:
      - platform: state
        entity_id: binary_sensor.michael_phone_is_docked_in_the_car
        from: "off"
        to: "on"
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "command_launch_app"
          data:
            package_name: "com.google.android.apps.maps"