powercalc:

template:
  - sensor:
      name: "Living Room Soundbar: Electric Consumption [kWh]"
      state: >-
        {{ (states('sensor.living_room_soundbar_smart_plug_power') | float(0)) / 1000 }}
      icon: mdi:flash
      unit_of_measurement: 'kWh'
      state_class: 'total_increasing'
      device_class: 'energy'
  - sensor:
      name: "Theatre Room TV: Electric Consumption [kWh]"
      state: >-
        {% if states('sensor.theatre_room_tv_smart_plug_power') not in ('unknown', 'unavailable') %}{{ float(states('sensor.theatre_room_tv_smart_plug_power')) / 1000 }}{% else %}0{% endif %}
      icon: mdi:flash
      unit_of_measurement: 'kWh'
      state_class: 'total_increasing'
      device_class: 'energy'