sensor:
  - platform: fitbit
    clock_format: 12H
    unit_system: metric
    monitored_resources:
      - "activities/calories"
      - "activities/distance"
      - "activities/minutesFairlyActive"
      - "activities/minutesLightlyActive"
      - "activities/minutesSedentary"
      - "activities/minutesVeryActive"
      - "activities/steps"
      - "activities/tracker/activityCalories"
      - "activities/tracker/calories"
      - "activities/tracker/distance"
      - "activities/tracker/minutesFairlyActive"
      - "activities/tracker/minutesLightlyActive"
      - "activities/tracker/minutesSedentary"
      - "activities/tracker/minutesVeryActive"
      - "activities/tracker/steps"
      - "body/bmi"
      - "body/fat"
      - "body/weight"