sensor:
  - platform: formulaone_api

input_boolean:
  formula_one_avoid_spoilers:
    name: Avoid F1 Spoilers?
    icon: mdi:car-sports

automation:
  - alias: Formula One - Automatically Play
    id: formula_one_automatically_play
    trigger: 
      - platform: calendar
        event: start
        entity_id: calendar.formula_1
        offset: -00:15:00
    condition:
      - condition: template
        value_template: "{{ state_attr('calendar.formula_1', 'message')|truncate(14, True, '') == 'F1: Grand Prix'}}"
      - condition: time
        before: "21:00:00"
      - condition: time
        after: "08:00:00"
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.all_rooms
          media_content_id: '/local/sounds/formula1.mp3'
          media_content_type: 'audio/mp3'
      - service: light.turn_off
        data:
          entity_id: light.theatre_room_ceiling
      - service: light.turn_on
        target:
          entity_id:
            - light.theatre_room_left_lamp
            - light.theatre_room_right_lamp
        data:
          brightness_pct: 20
          xy_color:  [0.5194, 0.4367] #mclaren papaya orange
      - service: light.turn_on
        target:
          entity_id: light.theatre_room_tv_cabinet_led_strip
        data:
          xy_color: [0.136, 0.04] #red bull blue
      - service: media_player.turn_on
        target:
          entity_id: media_player.theatre_room_tv
      - wait_template: "{{ is_state('media_player.theatre_room_tv', 'on') }}"
      - service: media_player.select_source
        data:
          entity_id: media_player.theatre_room_tv
          source: "Chromecast"

  - alias: Formula One - Hide Spoilers When Race Starts
    id: formula_one_hide_spoilers_when_race_starts
    trigger: 
      - platform: calendar
        event: start
        entity_id: calendar.formula_1
    condition:
      - condition: template
        value_template: "{{ state_attr('calendar.formula_1', 'message')|truncate(14, True, '') == 'F1: Grand Prix'}}"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.formula_one_avoid_spoilers