# Blank sensor to make the room headers look good
sensor:
  - platform: template
    sensors:
      blank:
        value_template: ''
        friendly_name: ''

# Lovelace Theme For Time Of Day
automation:
  - alias: Home Assistant Frontend - Set Theme at Startup
    initial_state: 'on'
    trigger:
    - platform: homeassistant
      event: start
    action:
      service: frontend.set_theme
      data_template:
        name: > 
          {% if is_state('sun.sun', 'above_horizon') %}
            midnight
          {% else %}
            midnight
          {% endif %}
          
  - alias: Home Assistant Frontend - Set dark theme at night
    initial_state: true
    trigger:
      - platform: state
        entity_id: sun.sun
        to: 'below_horizon'
    action:
      - service: frontend.set_theme
        data:
          name: midnight
            
  - alias: Home Assistant Frontend - Set light theme at day
    initial_state: true
    trigger:
      - platform: state
        entity_id: sun.sun
        to: 'above_horizon'
    action:
      - service: frontend.set_theme
        data:
          name: midnight

# Additional Panels
panel_iframe:
  home_server_dashboard:
    title: Home Server Dashboard
    url: !secret home_server_dashboard_url
    icon: mdi:monitor-dashboard
    require_admin: true
  recipe_manager:
    title: Recipe Manager
    url: !secret recipe_manager_url
    icon: mdi:food-variant
    require_admin: false
  mybgg:
    title: My Board Games
    url: !secret my_board_games_url
    icon: mdi:cards
    require_admin: false
panel_custom:
  - name: zwavegraph3 #graph of the zwave network
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    url_path: zwave-graph
    module_url: /local/zwavegraph3.js
    require_admin: true
    config:
      # ranker - pick one: network-simplex, tight-tree, longest-path
      ranker: network-simplex
      # edge_visibility - pick one: relevant, all
      edge_visibility: relevant
      # grouping - pick one: z-wave, ungrouped
      grouping: z-wave