automation:
  - alias: Front Door - Toggle Porch Light With Central Switch
    id: front_door_toggle_porch_light_with_central_switch
    variables: 
      #map the on/off buttons to the appropriate service
      buttons: 
        "on":
          service_to_call: light.turn_on
        "off":
          service_to_call: light.turn_off
    trigger: 
      - platform: event
        event_type: zha_event
        event_data: 
          device_ieee: !secret zha_central_switch_for_front_porch_light
    condition: 
      - "{{ trigger.event.data.command in buttons }}"
    action:
      - service: "{{ buttons[trigger.event.data.command].service_to_call }}"
        entity_id: light.front_porch_light

  - alias: Front Door - Turn On Porch Light If Front Door Opened After Sunset
    id: front_door_turn_on_porch_light_if_front_door_opened_after_sunset
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.front_screen_door
        from: "off"
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: state # from sunset until sunrise
          entity_id: sun.sun
          state: "below_horizon"
    action:
      - service: light.turn_on
        entity_id:
          - light.front_porch_light

  - alias: Front Door - Turn On Porch Light If Motion Detected
    id: front_door_turn_on_porch_light_if_motion_detected
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_person
        from: "off"
        to: "on"
    condition:
      - condition: state #from sunset until sunrise
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - service: scene.create #save the original state of the front porch light
        data:
          scene_id: front_porch_light_saved_state
          snapshot_entities:
            - light.front_porch_light
      - service: light.turn_on
        entity_id:
          - light.front_porch_light
      - wait_for_trigger: #wait for no motion, or 10 minutes, whichever is first
          - platform: state
            entity_id: binary_sensor.doorbell_person
            to: "off"
        timeout:
          minutes: 10
        continue_on_timeout: true
      - service: scene.turn_on #return front porch light to its previous state
        data:
          entity_id: scene.front_porch_light_saved_state

  - alias: Front Door - Notify Theatre TV If Motion Detected
    id: front_door_notify_theatre_tv_if_motion_detected
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_person
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: media_player.theatre_room_tv
        state: "on"
    action:
      - service: notify.theatre_room_tv
        data:
          message: "Somebody is at the front door."

  - alias: Front Door - When Doorbell Is Rung After Dark, Turn On Entry Hall Light
    id: front_door_when_doorbell_is_rung_after_dark_turn_on_entry_hall_light
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_visitor
        to: 'on'
    condition:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: scene.create
        data:
          scene_id: doorbell_entry_hall_previous_lights_state
          snapshot_entities:
            - light.entry_hall_lights
      - service: light.turn_on
        entity_id:
          - light.entry_hall_lights
      - delay:
          minutes: 5
      - service: scene.apply
        data:
          scene_id: doorbell_entry_hall_previous_lights_state

  - alias: Front Door - Turn Off Porch Light At Sunrise
    id: front_door_turn_off_porch_light_at_sunrise
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: light.turn_off
        entity_id:
          - light.front_porch_light

  - alias: Front Door - Toggle Side Hall Lights When Motion Detected
    id: front_door_toggle_side_hall_lights_when_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.side_hall_motion
    condition:
      - condition: state # from sunset until sunrise
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.side_hall_motion
                state: "off"
            sequence:
              #Turn off lights when no motion
              - service: light.turn_off
                target:
                  entity_id: light.side_hall
          - conditions:
              - condition: time
                before: "20:30:00"
            sequence:
                #Early evening, full brightness
              - service: light.turn_on
                target:
                  entity_id: light.side_hall
                data:
                  brightness_pct: 100
        default:
            #Night time, low brightness
          - service: light.turn_on
            target:
              entity_id: light.side_hall
            data:
              brightness_pct: 30

  - alias: Front Door - Turn On Front Porch Light When Ordering Food Delivery
    id: front_door_turn_on_front_porch_light_when_ordering_food_delivery
    variables:
      notifying_app: 
        package: "{{ state_attr('sensor.michael_s_galaxy_s10_last_notification', 'package') }}"
        title: "{{ state_attr('sensor.michael_s_galaxy_s10_last_notification', 'android.title') }}"
        text: "{{ state_attr('sensor.michael_s_galaxy_s10_last_notification', 'android.text') }}"
      known_delivery_apps:
        com.dd.doordash: #DoorDash
          notification_text: "your order has been picked up" #Android.text
        com.menulog.m: #Menulog
          notification_text: "Driver on the way" #Android.title
        com.ubercab.eats: #Uber Eats
          notification_text: "Your order is on the move!" #Android.text
    trigger:
      - platform: state
        entity_id: sensor.michael_s_galaxy_s10_last_notification #Look for new phone notiifations
    condition:
      - condition: state #from sunset until sunrise
        entity_id: sun.sun
        state: "below_horizon"
      - condition: state #Only turn on the light if I'm home currently.
        entity_id: person.michael
        state: "home"
      - condition: template #App notification is one of the recognised apps
        value_template: "{{ notifying_app.package in known_delivery_apps }}"
      - condition: template #App notification text or title is correct for delivery
        value_template: >-
          {{ known_delivery_apps[notifying_app.package].notification_text in (notifying_app.title|string)
          or known_delivery_apps[notifying_app.package].notification_text in (notifying_app.text|string) }}
    action:
      - service: light.turn_on
        entity_id: light.front_porch_light
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: The front porch light was turned on for your delivery driver.
          data:
            group: food_delivery
            notification_icon: "mdi:outdoor-lamp"
            actions:
              - action: "food_delivery_switch_off_light" 
                title: "Switch It Off"

  - alias: Front Door - Switch Off Front Porch Light From Mobile Notiifcation Action
    id: front_door_switch_off_front_porch_light_from_mobile_notification_action
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: food_delivery_switch_off_light
    action:
      - service: light.turn_off
        target:
          entity_id: light.front_porch_light

  - alias: Front Door - Send Michael Doorbell Notification
    id: front_door_send_michael_doorbell_notification
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_visitor
        to: 'on'
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          title: "Doorbell Rung"
          message: "Somebody is at the door!"
          data:
            group: "Doorbell Rung"
            image: /api/camera_proxy/camera.doorbell_main
            color: 'red'
            ttl: 0
            priority: high
            clickAction: "entityId:camera.doorbell_sub"
            vibrationPattern: "100, 1000, 100, 1000, 100, 1000, 100"
            channel: "Motion"
            notification_icon: "mdi:doorbell-video"
            car_ui: true
            sticky: true

  - alias: Front Door - Notify Michael If Person Detected
    id: front_door_notify_michael_if_person_detected
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_person
        from: "off"
        to: "on"
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "Someone might be at the door..."
          data:
            group: "Doorbell Motion"
            image: /api/camera_proxy/camera.doorbell_main
            color: 'red'
            ttl: 0
            priority: high
            clickAction: "entityId:camera.doorbell_sub"
            vibrationPattern: "100, 1000, 100, 1000, 100, 1000, 100"
            channel: "Motion"
            notification_icon: "mdi:doorbell-video"
            car_ui: true
            sticky: true
      - delay:
          minutes: 2 #Don't notify again straight away
