# Blank sensor to make the room headers look good
sensor:
  - platform: template
    sensors:
      blank:
        value_template: ''
        friendly_name: ''

panel_custom:
  - name: zwavegraph3 #graph of the zwave network
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    url_path: zwave-graph
    module_url: /local/zwavegraph3.js
    require_admin: true
    config:
      # ranker - pick one: network-simplex, tight-tree, longest-path
      ranker: network-simplex
      # edge_visibility - pick one: relevant, all
      edge_visibility: relevant
      # grouping - pick one: z-wave, ungrouped
      grouping: z-wave