cast:
  media_player:
    - host: !secret chromecast_theatre_ip_address
    - host: !secret chromecast_living_room_ip_address
    - host: !secret chromecast_audio_pc_ip_address
    - host: !secret google_home_bedroom__ip_address
    - host: !secret google_home_kitchen_ip_address
    - host: !secret google_home_office_ip_address
    - host: !secret google_home_theatre_ip_address
    - host: !secret google_home_ensuite_ip_address