cloud:
  google_actions:
    filter:
      exclude_domains:
        - media_player
        - automation
        - script
        - switch
        - group
        - cover
        - input_number
        - sensor
        - binary_sensor
        - alarm_control_panel
      include_entities:
        - script.set_movie_lighting
        - script.set_tv_dinner_lighting
        - script.set_party_lights
        - script.aircon_warm_master
        - script.aircon_fan_master
        - script.aircon_cool_central_living
        - script.time_for_a_movie
        - script.time_for_a_tv_dinner
        - script.time_for_star_wars
        - script.movie_has_finished
        - script.done_with_the_theatre_room
        - script.roomba_clean
        - switch.aircon_on_off
        - switch.aircon_zone_bed23
        - switch.aircon_zone_living
        - switch.aircon_zone_master
        - switch.aircon_zone_theatre
        # - switch.christmas_tree_power
        - group.aircon_vents
        - cover.theatre_blinds
        - media_player.theatre_room_tv
      exclude_entities:
        - light.theatre_room
        - light.theatre_room_2
        - light.fibaro_system_fgd212_dimmer_2_level_2
        - light.fibaro_system_fgd212_dimmer_2_level_4
        - light.office
        - light.office_2
        - light.range_extender_2
        - input_select.igrill_presets_probe
    entity_config:
      # switch.christmas_tree_power:
      #   name: Christmas Tree
      #   aliases:
      #     - Christmas Tree
      #     - Christmas Tree Switch
      #     - Christmas Tree Lights
      #     - Christmas Lights
      switch.aircon_on_off:
        name: Aircon
        aliases:
          - Aircon
          - Airconditioner
      switch.aircon_zone_bed23:
        name: Front Room Vents
        aliases:
          - Front Room Vents
          - Study Vent
          - Office Vent
          - Sewing Room Vent
      switch.aircon_zone_living:
        name: Center House Vents
        aliases:
          - Center House Vents
          - Living Room Vent
          - Dining Room Vent
          - Central Living Vents
      switch.aircon_zone_master:
        name: Master Bedroom Vent
        aliases:
          - Master Bedroom Vent
          - Bedroom Vent
      switch.aircon_zone_theatre:
        name: Theatre Room Vent
        aliases:
          - Theatre Room Vent
          - Theatre Vent
      light.alfresco_fairy_lights:
        name: Alfresco Fairy Lights
        aliases:
          - Fairy Lights

# Text to speech
tts:
  - platform: google_translate