input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:account-multiple-plus

automation:
  #When guests are staying over night, disable certain automations
  - alias: Guests - Activate Guest Mode
    trigger: 
      - platform: state
        entity_id: input_boolean.guest_mode
        to: "on"
    action:
      - service: automation.turn_off
        data:
          entity_id: 
            - automation.theatre_room_blinds_open_automatically
            - automation.theatre_room_motion_turn_on_lights_when_motion_detected
            - automation.theatre_room_lights_turn_off_lamps_after_no_activity

  #When guests go home, reactivate automations
  - alias: Guests - Deactivate Guest Mode
    trigger: 
      - platform: state
        entity_id: input_boolean.guest_mode
        to: "off"
    action:
      - service: automation.turn_on
        data:
          entity_id: 
            - automation.theatre_room_blinds_open_automatically
            - automation.theatre_room_motion_turn_on_lights_when_motion_detected
            - automation.theatre_room_lights_turn_off_lamps_after_no_activity

  #Once per day, ask if guest mode should be deactivated
  - alias: Guests - Notification To Deactivate Guest Mode
    trigger:
      - platform: time
        at: '12:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "on"
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: Guest mode is on. Should it be turned off?
          data:
            actions:
              - action: "deactivate_guest_mode" 
                title: "Deactive Guest Mode"

  #When "Deactive Guest Mode" button on notification is pressed, do what it says!                 
  - alias: Guests - Deactivate Guest Mode On Notification Button Pressed
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: deactivate_guest_mode
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.guest_mode