light:
  - platform: group
    name: Kitchenette Lights
    entities:
      - light.scullery_light
      - light.pantry_light
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_ceiling_light
      - light.kitchen_island
  - platform: group
    name: Scullery LEDs
    entities:
      - light.scullery_leds_large_light
      - light.scullery_leds_small_light

sensor:
  - platform: history_stats
    name: Coffees Made Today
    entity_id: binary_sensor.coffee_machine
    state: "off"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

binary_sensor:
  - platform: template
    sensors:
      dishwasher:
        friendly_name: "Dishwasher"
        value_template: "{{ states('sensor.dishwasher_smart_plug_power')|float > 5 }}"
        icon_template: >-
          {% if is_state("binary_sensor.dishwasher", "on") %}
            mdi:dishwasher
          {% else %}
            mdi:dishwasher-off
          {% endif %}

automation:
  - alias: Kitchen - Turn On Main Fridge When It Turns Itself Off
    id: kitchen_turn_on_main_fridge_when_it_turns_itself_off
    mode: queued
    trigger:
      - platform: state
        entity_id: switch.main_fridge_smart_plug
        to: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.main_fridge_smart_plug
      - delay:
          minutes: 5
  - alias: Kitchen - Turn On Drinks Fridge When It Turns Itself Off
    id: kitchen_turn_on_drinks_fridge_when_it_turns_itself_off
    mode: queued
    trigger:
      - platform: state
        entity_id: switch.drinks_fridge_smart_plug
        to: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.drinks_fridge_smart_plug
      - delay:
          minutes: 5

  - alias: Kitchen - Toggle Scullery Lights When Motion Detected
    id: kitchen_toggle_scullery_lights_when_motion_detected
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.scullery_ep1_pir
          - binary_sensor.scullery_ep1_occupancy
          - binary_sensor.pantry_motion_sensor_motion
    action:
      - choose:
          - conditions:
              - alias: Trigger was motion detected in the scullery
                condition: template
                value_template: >-
                  {{
                    trigger.entity_id == "binary_sensor.scullery_ep1_pir"
                    and trigger.to_state.state == 'on'
                  }}
            sequence:
              - alias: Turn on scullery LEDs
                service: light.turn_on
                target:
                  entity_id: light.scullery_leds
                data:
                  brightness_pct: 1
          - conditions:
              - alias: Trigger was motion detected in the pantry
                condition: template
                value_template: >-
                  {{
                    trigger.entity_id == "binary_sensor.pantry_motion_sensor_motion"
                    and trigger.to_state.state == 'on'
                  }}
            sequence:
              - alias: Turn on pantry light
                service: light.turn_on
                target:
                  entity_id: light.pantry_light
          - conditions:
              - alias: Trigger was pantry motion no longer detected
                condition: template
                value_template: >-
                  {{
                    trigger.entity_id == "binary_sensor.pantry_motion_sensor_motion"
                    and trigger.to_state.state == 'off'
                  }}
            sequence:
              - alias: Turn off pantry light
                service: light.turn_off
                target:
                  entity_id: light.pantry_light
          - conditions:
              - alias: Trigger was scullery occupancy no longer detected
                condition: template
                value_template: >-
                  {{
                    trigger.entity_id == "binary_sensor.scullery_ep1_occupancy"
                    and trigger.to_state.state == 'off'
                  }}
            sequence:
              - alias: Turn off all lights
                service: light.turn_off
                target:
                  entity_id:
                    - light.kitchenette_lights
                    - light.scullery_leds

  - alias: Kitchen - Toggle Scullery Lights When Button Pressed
    id: kitchen_toggle_scullery_lights_when_button_pressed
    mode: restart
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: !secret zha_scullery_light_switch
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == 'off' }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.kitchenette_lights
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == 'on'}}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.kitchenette_lights
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == 'press' and trigger.event.data.params.param1 == 257 }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.scullery_leds
                data:
                  brightness_pct: 1
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == 'press' and trigger.event.data.params.param1 == 256 }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.scullery_leds

  - alias: Kitchen - Turn On Lights Using Island Switch
    id: kitchen_turn_on_lights_using_island_switch
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: !secret zha_kitchen_island_lights_switch
          command: "on"
    action:
      - choose:
          # If ceiling lights are off, turn them on
          - conditions:
              - condition: state
                entity_id: light.kitchen_ceiling_light
                state: "off"
            sequence:
              - service: light.turn_on
                entity_id: light.kitchen_ceiling_light
        # Otherwise turn on the kitchen island light
        default:
          - service: light.turn_on
            entity_id: light.kitchen_island
  - alias: Kitchen - Turn Off Lights Using Island Switch
    id: kitchen_turn_off_lights_using_island_switch
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: !secret zha_kitchen_island_lights_switch
          command: "off"
    action:
      - choose:
          # If kitchen island lights are on, turn them off
          - conditions:
              - condition: state
                entity_id: light.kitchen_island
                state: "on"
            sequence:
              - service: light.turn_off
                entity_id: light.kitchen_island
        # Otherwise turn of the ceiling light
        default:
          - service: light.turn_off
            entity_id: light.kitchen_ceiling_light
  - alias: Kitchen - Turn On Dishwasher Smart Switch When It Turns Itself Off
    id: kitchen_turn_on_dishwasher_smart_switch_when_it_turns_itself_off
    mode: queued
    max: 3
    trigger:
      - platform: state
        entity_id: switch.dishwasher_smart_plug
        to: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.dishwasher_smart_plug
      - delay:
          minutes: 5

alert:
  drinks_fridge_door_alerts:
    title: Drinks Fridge Left Open
    name: The drinks fridge door was left open!
    entity_id: binary_sensor.drinks_fridge_door
    state: "on"
    repeat:
      - 3 #minutes to wait before the first alert
      - 1 #minues between alerts once started
    can_acknowledge: false
    skip_first: true
    notifiers:
      - mobile_app_pixel_8_pro
      - mobile_app_lauras_iphone
      - theatre_room_tv
    data:
      notification_icon: "mdi:fridge-industrial-alert-outline"
      group: Drinks Fridge Door
      color: "red"
      ttl: 0
      priority: high

  kitchen_sink_leak_alerts:
    title: Leak detected!
    name: The kitchen sink or dishwasher is leaking!
    entity_id: binary_sensor.water_sensor_kitchen_sink
    state: "on"
    repeat:
      - 1
    can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_pixel_8_pro
      - mobile_app_lauras_iphone
      - theatre_room_tv
    data:
      notification_icon: "mdi:water-alert"
      group: Kitchen Sink Leak
      color: "red"
      ttl: 0
      priority: high

  main_fridge_power_alerts:
    title: Main Fridge Has No Power!
    name: The main fridge's smart plug is turned off.
    entity_id: switch.main_fridge_smart_plug
    state: "off"
    repeat:
      - 5 #minutes to wait before the first alert
      - 1 #minues between alerts once started
    can_acknowledge: false
    skip_first: true
    notifiers:
      - mobile_app_pixel_8_pro
      - mobile_app_lauras_iphone
      - theatre_room_tv
    data:
      notification_icon: "mdi:fridge-industrial-alert-outline"
      group: Fridges
      color: "red"
      ttl: 0
      priority: high
