light:
  - platform: group
    name: Kitchenette Lights
    entities:
      - light.scullery_light
      - light.pantry_light
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_ceiling_light
      - light.kitchen_island

sensor:
  - platform: history_stats
    name: Coffees Made Today
    entity_id: binary_sensor.coffee_machine
    state: 'off'
    type: count
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

binary_sensor:
  - platform: template
    sensors:
      dishwasher:
        friendly_name: "Dishwasher"
        value_template: "{{ states('sensor.dishwasher_smart_plug_power')|float > 5 }}"
        icon_template: >-
          {% if is_state("binary_sensor.dishwasher", "on") %}
            mdi:dishwasher
          {% else %}
            mdi:dishwasher-off
          {% endif %}
  - platform: template
    sensors:
      kitchen_chair_1_upright:
        friendly_name: "Kitchen Chair 1 Upright"
        icon_template: mdi:table-chair
        value_template: >-
          {{ state_attr('binary_sensor.kitchen_chair_vibration_1', 'orientation')[2] <= 0 }}
      kitchen_chair_2_upright:
        friendly_name: "Kitchen Chair 2 Upright"
        icon_template: mdi:table-chair
        value_template: >-
          {{ state_attr('binary_sensor.kitchen_chair_vibration_2', 'orientation')[2] <= 0 }}
      kitchen_chair_3_upright:
        friendly_name: "Kitchen Chair 3 Upright"
        icon_template: mdi:table-chair
        value_template: >-
          {{ state_attr('binary_sensor.kitchen_chair_vibration_3', 'orientation')[2] <= 0 }}
      kitchen_chair_4_upright:
        friendly_name: "Kitchen Chair 4 Upright"
        icon_template: mdi:table-chair
        value_template: >-
          {{ state_attr('binary_sensor.kitchen_chair_vibration_4', 'orientation')[2] <= 0 }}
      any_kitchen_chair_upright:
        friendly_name: "Any Kitchen Chair Upright"
        icon_template: mdi:table-chair
        value_template: >-
          {{  states('binary_sensor.kitchen_chair_1_upright') == 'on'  or
              states('binary_sensor.kitchen_chair_2_upright') == 'on'  or 
              states('binary_sensor.kitchen_chair_3_upright') == 'on'  or
              states('binary_sensor.kitchen_chair_4_upright') == 'on'  }} 

automation:
  - alias: Kitchen - Turn On Main Fridge When It Turns Itself Off
    id: kitchen_turn_on_main_fridge_when_it_turns_itself_off
    mode: queued
    trigger:
      - platform: state
        entity_id: switch.main_fridge_smart_plug
        to: 'off'
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.main_fridge_smart_plug
      - delay:
          minutes: 5
  - alias: Kitchen - Turn On Drinks Fridge When It Turns Itself Off
    id: kitchen_turn_on_drinks_fridge_when_it_turns_itself_off
    mode: queued
    trigger:
      - platform: state
        entity_id: switch.drinks_fridge_smart_plug
        to: 'off'
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.drinks_fridge_smart_plug
      - delay:
          minutes: 5
  #if coffee machine left open, send a push notification.
  - alias: Kitchen - Notify If Coffee Machine Closed for 5 Minutes
    id: kitchen_notify_if_coffee_machine_closed_for_5_minutes
    trigger:
      platform: time_pattern
      minutes: '/5' #run every 5 minutes
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.coffee_machine
          state: 'off'
          for:
            minutes: 4
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: The coffee machine was left closed.
      - service: notify.mobile_app_lauras_iphone
        data:
          message: The coffee machine was left closed.
      - condition: state
        entity_id: media_player.kitchen_google_home_hub
        state: 'off' #Only use text-to-speech on Google Home Hub if it's not already in use, so it doesn't stop any music from playing
      - service: tts.google_translate_say
        data:
          entity_id: media_player.kitchen_google_home_hub
          message: The coffee machine was left closed.

  - alias: Kitchen - Toggle Scullery Lights When Motion Detected
    id: kitchen_toggle_scullery_lights_when_motion_detected
    trigger: 
      - platform: state
        entity_id: binary_sensor.scullery_motion
    action:
      - service: "{% if states.binary_sensor.scullery_motion.state == 'on' -%} light.turn_on {%- else -%} light.turn_off {%- endif %}"
        entity_id: 
          - light.scullery_light
          - light.pantry_light

  - alias: Kitchen - Turn On Lights Using Island Switch
    id: kitchen_turn_on_lights_using_island_switch
    trigger: 
      - platform: event
        event_type: deconz_event
        event_data: 
          id: kitchen_lights_switch
          event: 1002 #on switch
    action:
      - choose:
        # If ceiling lights are off, turn them on
          - conditions:
              - condition: state
                entity_id: light.kitchen_ceiling_light
                state: "off"
            sequence: 
              - service: light.turn_on
                entity_id: light.kitchen_ceiling_light
        # Otherwise turn on the kitchen island light
        default:
          - service: light.turn_on
            entity_id: light.kitchen_island

  - alias: Kitchen - Turn Off Lights Using Island Switch
    id: kitchen_turn_off_lights_using_island_switch
    trigger: 
      - platform: event
        event_type: deconz_event
        event_data: 
          id: kitchen_lights_switch
          event: 2002 #off switch
    action:
      - choose:
        # If kitchen island lights are on, turn them off
          - conditions:
              - condition: state
                entity_id: light.kitchen_island
                state: "on"
            sequence: 
              - service: light.turn_off
                entity_id: light.kitchen_island
        # Otherwise turn of the ceiling light
        default:
          - service: light.turn_off
            entity_id: light.kitchen_ceiling_light
  - alias: Kitchen - Turn On Dishwasher Smart Switch When It Turns Itself Off
    id: kitchen_turn_on_dishwasher_smart_switch_when_it_turns_itself_off
    mode: queued
    max: 3
    trigger:
      - platform: state
        entity_id: switch.dishwasher_smart_plug
        to: 'off'
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.dishwasher_smart_plug
      - delay:
          minutes: 5

alert:
  drinks_fridge_door_alerts:
    title: Drinks Fridge Left Open
    name: The drinks fridge door was left open! 
    entity_id: binary_sensor.drinks_fridge_door
    state: 'on'
    repeat: 
      - 3 #minutes to wait before the first alert
      - 1 #minues between alerts once started
    can_acknowledge: false
    skip_first: true
    notifiers:
      - mobile_app_michael_s_galaxy_s10
      - mobile_app_lauras_iphone
    data:
      group: Drinks Fridge Door
      color: 'red'
      ttl: 0
      priority: high

  kitchen_sink_leak_alerts:
    title: Leak detected! 
    name: The kitchen sink or dishwasher is leaking! 
    entity_id: binary_sensor.water_sensor_kitchen_sink
    state: 'on'
    repeat: 
      - 1 
    can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_michael_s_galaxy_s10
      - mobile_app_lauras_iphone
    data:
      group: Kitchen Sink Leak
      color: 'red'
      ttl: 0
      priority: high

  main_fridge_power_alerts:
    title: Main Fridge Has No Power!
    name: The main fridge's smart plug is turned off.
    entity_id: switch.main_fridge_smart_plug
    state: 'off'
    repeat: 
      - 5 #minutes to wait before the first alert
      - 1 #minues between alerts once started
    can_acknowledge: false
    skip_first: true
    notifiers:
      - mobile_app_michael_s_galaxy_s10
      - mobile_app_lauras_iphone
    data:
      group: Fridges
      color: 'red'
      ttl: 0
      priority: high
