light:
  - platform: switch
    name: Laundry LED Strip
    entity_id: switch.laundry_led_smart_plug
  - platform: group
    name: Washing Line Lights
    entities:
      - light.washing_line_light_1
      - light.washing_line_light_2

sensor:
  - platform: template
    sensors:
      washing_machine_power_consumption:
        friendly_name: "Washing Machine Power Consumption"
        unit_of_measurement: "w"
        value_template: "{{ state_attr('switch.washing_machine', 'current_power_w') }}"

binary_sensor:
  - platform: template
    sensors:
      #if power consumption is high enough, washing machine is running
      washing_machine_running:
        friendly_name: "Washing Machine Is Running"
        value_template: "{{ states('sensor.washing_machine_power_consumption')|float > 5 }}"
        delay_off:
          minutes: 10 #Power consumption must be low for 10 minutes before considering the washing machine off
        icon_template: >-
          {% if is_state("binary_sensor.washing_machine_running", "on") %} 
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
      #If the door hasn't been opened since the machine last turned off
      washing_machine_needs_emptying:
        friendly_name: "Washing Machine Needs Emptying"
        value_template: >- #FIXME: There is a logic error here caused when HA restarts, the last_changed values might not be in the correct order
          {{
            as_timestamp(states.binary_sensor.washing_machine_door.last_changed) 
              < as_timestamp(states.binary_sensor.washing_machine_running.last_changed) 
           and is_state('binary_sensor.washing_machine_running', 'off')
           and is_state('binary_sensor.washing_machine_door', 'off')
          }}
        icon_template: mdi:washing-machine-alert
        device_class: problem
      #If the laundry humidity is too high and the outside door is closed
      laundry_dryer_running_with_door_closed:
        friendly_name: "Dryer Running With Door Closed"
        value_template: >-
          {{
            states.sensor.laundry_humidity.state|float >= 90.0
            and states.binary_sensor.laundry_door.state == 'off'
          }}
        icon_template: mdi:water-percent-alert
        device_class: problem

automation:
  - alias: Laundry - Turn On Laundry Lights When Button Pressed
    id: laundry_turn_on_laundry_lights_when_button_pressed
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: laundry_wall_switch
          event: 1002 #single press, left button
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.laundry_ceiling
                state: "off"
            sequence:
              - service: light.turn_on
                entity_id:
                  - light.laundry_led_strip
                  - light.laundry_ceiling
                data:
                  brightness_pct: 100
          - conditions:
              - condition: state
                entity_id: light.laundry_ceiling
                state: "on"
            sequence:
              - service: light.turn_off
                entity_id:
                  - light.laundry_led_strip
                  - light.laundry_ceiling

  - alias: Laundry - Turn On Washing Line Lights When Button Pressed
    id: laundry_turn_on_washing_line_lights_when_button_pressed
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: laundry_wall_switch
          event: 2002 #single press, right button
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.washing_line_lights
                state: "off"
            sequence:
              - service: light.turn_on
                entity_id: light.washing_line_lights
                data:
                  brightness_pct: 100
          - conditions:
              - condition: state
                entity_id: light.washing_line_lights
                state: "on"
            sequence:
              - service: light.turn_off
                entity_id: light.washing_line_lights

  - alias: Laundry - Toggle Washing Line Lights When Door Opened
    id: laundry_toggle_washing_line_lights_when_door_opened
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.laundry_door
          - binary_sensor.garage_door_external
        from: "off"
        to: "on"
      - platform: state
        entity_id:
          - binary_sensor.laundry_door
          - binary_sensor.garage_door_external
        to: "off"
        for: "00:02:00" #if both doors closed for 2 minutes
    condition:
      - condition: state # from sunset until sunrise
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  # from just before sunset until sunrise
                  - condition: sun
                    after: sunset
                    after_offset: "-00:30:00"
                  # Either door has been opened
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: binary_sensor.laundry_door
                        state: "on"
                      - condition: state
                        entity_id: binary_sensor.garage_door_external
                        state: "on"
            sequence:
              - service: light.turn_on
                entity_id: light.washing_line_lights
                data:
                  brightness_pct: 100
          - conditions:
              # Both doors have been closed for 2 minutes
              - condition: state
                entity_id:
                  - binary_sensor.laundry_door
                  - binary_sensor.garage_door_external
                state: "off"
                for:
                  minutes: 2
            sequence:
              - service: light.turn_off
                entity_id: light.washing_line_lights

  - alias: Laundry - Turn On Laundry LED Lights When Motion Detected
    id: laundry_turn_on_laundry_led_lights_when_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_motion
        to: "on"
    condition:
      - condition: state # from sunset until sunrise
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - service: light.turn_on
        entity_id:
          - light.laundry_led_strip

  - alias: Laundry - Turn Off Lights When No Motion Detected
    id: laundry_turn_off_lights_when_no_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_motion
        to: "off"
    action:
      - service: light.turn_off
        entity_id:
          - light.laundry_led_strip

  - alias: Laundry - Notify If Putting Washing Up And It Will Rain Soon
    id: laundry_notify_if_putting_washing_up_and_it_will_rain_soon
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_line
        from: "off"
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.weather_it_is_raining_today
            state: "on"
          - condition: state
            entity_id: binary_sensor.weather_it_is_raining_tomorrow
            state: "on"
    variables:
      notification_message: >-
        {% if states('binary_sensor.weather_it_is_raining_today') == "on" -%}
          Today's forecast is {{ states('sensor.weather_conditions_today') }} - are you sure you want to hang out the washing?
        {%- else -%}
          Tomorrow's forecast is {{ states('sensor.weather_conditions_tomorrow') }} - are you sure you want to hang out the washing?
        {%- endif %}
    action:
      - service: notify.mobile_app_lauras_iphone
        data:
          message: "{{ notification_message }}"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "{{ notification_message }}"
          data:
            group: "Washing Line"

  - alias: Laundry - Notify If There Is Washing Already On The Line And It Will Rain Tomorrow
    id: laundry_notify_if_there_is_washing_already_on_the_line_and_it_will_rain_tomorrow
    trigger: # trigger when sun sets or tomorrow's forecast changes after 8pm
      - platform: time
        at: "20:00:00"
      - platform: state
        entity_id: binary_sensor.weather_it_will_rain_tomorrow
        from: "off"
        to: "on"
    condition:
      - condition: time
        after: "20:00:00"
      - condition: state # and it will rain tomorrow
        entity_id: binary_sensor.weather_it_will_rain_tomorrow
        state: "on"
      - condition: state # and there is washing already on the line
        entity_id: binary_sensor.washing_line
        state: "on"
    variables:
      notification_message: There's a chance of rain tomorrow - make sure to bring in the washing.
    action:
      - service: notify.mobile_app_lauras_iphone
        data:
          message: "{{ notification_message }}"
      - wait_template: "{{ is_state('person.michael', 'home') }}" # wait until I'm home to notify me, as I can't do anything about it if I'm not!
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "{{ notification_message }}"
          data:
            group: "Washing Line"

  - alias: Laundry - Notify If There Is Washing Already On The Line And It Is Starting To Rain
    id: laundry_notify_if_there_is_washing_already_on_the_line_and_it_is_starting_to_rain
    trigger:
      - platform: state
        entity_id: binary_sensor.weather_it_is_raining_today
        from: "off"
        to: "on"
    condition:
      - condition: state # there is washing already on the line
        entity_id: binary_sensor.washing_line
        state: "on"
    variables:
      notification_title: Rain imminent!
      notification_message: It is about to rain, you should bring in the washing!
    action:
      - service: notify.mobile_app_lauras_iphone
        data:
          title: "{{ notification_title }}"
          message: "{{ notification_message }}"
      - wait_template: "{{ is_state('person.michael', 'home') }}" # wait until I'm home to notify me, as I can't do anything about it if I'm not!
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          title: "{{ notification_title }}"
          message: "{{ notification_message }}"
          data:
            group: "Washing Line"
            color: "red"
            ttl: 0
            priority: high
      - condition: time
        before: "22:00:00" # Don't send any house-wide announcements after 10pm as people might be trying to sleep
      - condition: state
        entity_id: media_player.kitchen_google_home_hub
        state: "off" # Only use text-to-speech on Google Home Hub if it's not already in use, so it doesn't stop any music from playing
      - service: tts.google_translate_say
        data:
          entity_id: media_player.all_rooms
          message: "{{ notification_message }}"

alert:
  laundry_humidity_alert:
    name: The laundry humidity is too high - please open the door.
    entity_id: binary_sensor.laundry_dryer_running_with_door_closed
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_michael_s_galaxy_s10
    data:
      group: Laundry Humidity