light:
  - platform: switch
    name: Laundry LED Strip
    entity_id: switch.laundry_led_smart_plug

sensor:
  - platform: template
    sensors:
      washing_machine_power_consumption:
        friendly_name: "Washing Machine Power Consumption"
        unit_of_measurement: "w"
        value_template: "{{ state_attr('switch.washing_machine', 'current_power_w') }}"

binary_sensor:
  - platform: template
    sensors:
      #if power consumption is high enough, washing machine is running
      washing_machine_running:
        friendly_name: "Washing Machine Is Running"
        value_template: "{{ states('sensor.washing_machine_power_consumption')|float > 5 }}"
        delay_off:
          minutes: 10 #Power consumption must be low for 10 minutes before considering the washing machine off
        icon_template: >-
          {% if is_state("binary_sensor.washing_machine_running", "on") %} 
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
      #If the door hasn't been opened since the machine last turned off
      washing_machine_needs_emptying:
        friendly_name: "Washing Machine Needs Emptying"
        value_template: >-
          {{
            as_timestamp(states.binary_sensor.washing_machine_door.last_changed) 
              < as_timestamp(states.binary_sensor.washing_machine_running.last_changed) 
           and is_state('binary_sensor.washing_machine_running', 'off')
           and is_state('binary_sensor.washing_machine_door', 'off')
          }}
        icon_template: mdi:washing-machine-alert
        device_class: occupancy

automation:
  - alias: Laundry - Turn On Lights When Motion Detected
    trigger: 
      - platform: state
        entity_id: binary_sensor.laundry_motion
        to: 'on'
    condition:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: 
          - light.laundry_led_strip

  - alias: Laundry - Turn Off Lights When No Motion Detected
    trigger: 
      - platform: state
        entity_id: binary_sensor.laundry_motion
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: 
          - light.laundry_led_strip