
script:
  turn_off_living_room_tv:
    sequence:
      - condition: state
        entity_id: binary_sensor.living_room_tv
        state:  "on"
      - service: remote.send_command
        target:
          entity_id: remote.broadlink_rm_pro_roomba_remote
        data:
          command: b64:JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA=
  turn_on_living_room_tv:
    sequence:
      - condition: state
        entity_id: binary_sensor.living_room_tv
        state:  "off"
      - service: remote.send_command
        target:
          entity_id: remote.broadlink_rm_pro_roomba_remote
        data:
          command: b64:JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA=

binary_sensor:
  - platform: template
    sensors:
      living_room_tv:
        friendly_name: "Living Room TV"
        value_template: "{{ states('sensor.living_room_tv_power')|float > 10 }}"
        icon_template: >-
          {% if is_state("binary_sensor.living_room_tv", "on") %}
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}

switch:
  - platform: template
    switches:
      living_room_tv:
        friendly_name: Living Room TV
        value_template: "{{ is_state('binary_sensor.living_room_tv', 'on') }}"
        turn_on:
          service: script.turn_on_living_room_tv
        turn_off:
          service: script.turn_off_living_room_tv
        icon_template: >-
          {% if is_state("binary_sensor.living_room_tv", "on") %} 
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}