scene:
  - name: Living Room - Soft Lighting
    icon: "mdi:globe-light"
    entities:
      light.genio_bulb_lantern_pink:
        state: "on"
        rgb_color:
          - 255
          - 0
          - 225
        brightness_pct: 25
      light.genio_bulb_lantern_purple:
        state: "on"
        rgb_color:
          - 255
          - 0
          - 250
        brightness_pct: 25
      light.dining_room_table_lamp:
        state: "on"
        rgb_color:
          - 255
          - 206
          - 64
        brightness: 165
      light.living_room_tv_led_strip_local:
        state: "on"
        rgb_color:
          - 255
          - 63
          - 15
        brightness_pct: 50
      light.curtain_left:
        state: "on"
        effect: "1 Peachy Soft Tra" #nice soft light
        brightness_pct: 15
      light.living_room:
        state: "off"
      light.dining_room: 
        state: "off"
      # light.kitchen_ceiling_light:
      #   state: "off"

automation: 
  - alias: Dining Room - Toggle Dining Room Table Lamp With Button
    id: dining_room_toggle_dining_room_table_lamp_with_button
    trigger: 
      - platform: event
        event_type: zha_event
        event_data: 
          device_ieee: !secret zha_dining_room_table_lamp_button
    action:
      - service: light.toggle
        target:
          entity_id: light.dining_room_table_lamp
        data:
          rgb_color:
            - 255
            - 206
            - 64
          brightness: 165

  - alias: Living Room - Change Soundbar Input When Tv Power Toggled
    id: living_room_change_soundbar_input_when_tv_power_toggled
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_tv
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_tv
              state: 'off'
          sequence: 
            - service: script.living_room_soundbar_set_channel
              data:
                channel: 'chromecast'
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_tv
              state: 'on'
          sequence: 
            - service: script.living_room_soundbar_set_channel
              data:
                channel: 'tv'
  - alias: Living Room - Turn On TV Smart Switch When It Turns Itself Off
    id: living_room_turn_on_tv_smart_switch_when_it_turns_itself_off
    mode: queued
    max: 3
    trigger:
      - platform: state
        entity_id: switch.living_room_tv_smart_plug
        to: 'off'
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.living_room_tv_smart_plug
      - delay:
          minutes: 5

  - alias: Living Room - Change LED Strip When TV Power Toggles
    id: living_room_change_led_strip_when_tv_power_toggled
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_tv
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_tv
              state: 'off'
          sequence: 
            - service: light.turn_off
              target:
                entity_id: light.living_room_tv_led_strip_local
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_tv
              state: 'on'
          sequence: 
            - service: light.turn_on
              data:
                brightness_pct: 100
                rgb_color:
                  - 0
                  - 255
                  - 255
              target:
                entity_id: light.living_room_tv_led_strip_local

  - alias: Living Room - Turn On Soft Lights At Night
    id: living_room_turn_on_soft_lights_at_night
    mode: single
    trigger:
      - platform: sun
        event: sunset
    condition:
      #Only run when we are home
      - condition: state
        entity_id: 'binary_sensor.someone_home'
        state: 'on'
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.living_room_soft_lighting

  - alias: Living Room - Turn On Soft Lighting If Arriving Home After Sunset
    id: living_room_turn_on_soft_lighting_if_arriving_home_after_sunset
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_home
        from: 'off'
        to: 'on'
    condition:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.living_room_soft_lighting

script:
  turn_off_living_room_tv:
    sequence:
      - condition: state
        entity_id: binary_sensor.living_room_tv
        state:  "on"
      - service: remote.send_command
        target:
          entity_id: remote.living_room_broadlink_remote
        data:
          command: b64:JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA=
  turn_on_living_room_tv:
    sequence:
      - condition: state
        entity_id: binary_sensor.living_room_tv
        state:  "off"
      - service: remote.send_command
        target:
          entity_id: remote.living_room_broadlink_remote
        data:
          command: b64:JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAFGgABKEoSAAxWDQUAAAAAAAA=
  living_room_soundbar_turn_on:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.living_room_broadlink_remote
        data:
          command: b64:JgBYAAABO5YSOhI5FDgUOBY2FTYUOBY2FBMVERQTFBIUExQSFBMUExMTFDgUOBQSFBMUEhYRFhETOBQTFBIUOBY2EjoTOBM5FAAFEAABPEsTAAxTAAE9ShQADQU=
  living_room_soundbar_change_source:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.living_room_broadlink_remote
        data:
          command: b64:JgBYAAABO5YUOBM5FDcUOBQ4EzkSOhQ3FBMUExQSFBMUEhQTFBMTExQTFBIUOBQTFBIUExQ4ExMUOBQ4FBIUOBM5FDgSFBY2EwAFEgABPEsUAAxTAAE9ShIADQU=
  living_room_soundbar_mute:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.living_room_broadlink_remote
        data:
          command: b64:JgBYAAABO5YSOhM4EzkUOBI6FDcUOBQ4EhUTExQTFBIUExQTExMUExM4FBMUOBIUFjYTFBQSFBMUEhQ4ExQWNhMTFDgUOBI5EwAFEgABPUoSAAxUAAE8SxQADQU=
  living_room_soundbar_volume_down:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.living_room_broadlink_remote
        data:
          command: b64:JgBYAAABPJUUOBM5FDgTORQ4FTYTORM5FBMTExQTFBIWERQSFBMUExMTFBMVERQ4FDgUEhQTFBIUOBM5FDgUEhQTFDgVNhQ4EwAFEgABPUsVAAxSAAE9SxMADQU=
  living_room_soundbar_volume_up:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.living_room_broadlink_remote
        data:
          command: b64:JgBgAAABPpUUOBY2EzkUOBM4EzkTORQ4EhQUExQSFBMUExMTFBMUEhQTFBMTOBQTFDgSFBQTFBIUOBM5FBMTOBMUFDgSORQ4FQAFEAABPUoUAAxTAAE8ShQADFMAATtMFAANBQAAAAAAAAAA
  living_room_soundbar_set_channel:
    fields: 
      channel: 
        description: 'Which input should be selected for the soundbar?'
        example: 'tv'
    variables: 
      channel_source_switches:
        'bluetooth': 
          source_switch_count: 0
        'radio': 
          source_switch_count: 1
        'tv': 
          source_switch_count: 2
        'chromecast': 
          source_switch_count: 3
    sequence:
      - service: switch.turn_off
        entity_id: switch.living_room_soundbar_smart_plug
      - delay:
          seconds: 8
      - service: switch.turn_on
        entity_id: switch.living_room_soundbar_smart_plug
      - delay:
          seconds: 3
      - service: script.living_room_soundbar_turn_on
      - delay:
          seconds: 2
      - repeat:
          count: "{{ channel_source_switches[channel].source_switch_count }}"
          sequence:
            - service: script.living_room_soundbar_change_source
            - delay:
                seconds: 1

binary_sensor:
  - platform: template
    sensors:
      living_room_tv:
        friendly_name: "Living Room TV"
        value_template: "{{ states('sensor.living_room_tv_smart_plug_power')|float > 10 }}"
        icon_template: >-
          {% if is_state("binary_sensor.living_room_tv", "on") %}
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}

switch:
  - platform: template
    switches:
      living_room_tv:
        friendly_name: Living Room TV
        value_template: "{{ is_state('binary_sensor.living_room_tv', 'on') }}"
        turn_on:
          service: script.turn_on_living_room_tv
        turn_off:
          service: script.turn_off_living_room_tv
        icon_template: >-
          {% if is_state("binary_sensor.living_room_tv", "on") %} 
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}