binary_sensor:

  #If the humidity is high and not dropping quickly, the shower is on
  - platform: threshold
    name: Ensuite Shower Above Humidity Threshold
    entity_id: sensor.ensuite_shower_humidity
    upper: 92
  - platform: trend
    sensors:
      ensuite_shower_humidity_falling:
        entity_id: sensor.ensuite_shower_humidity
        sample_duration: 3600 #last 1 hour
        min_gradient: -0.002 #Humidity is dropping fast enough
        max_samples: 5
  - platform: template
    sensors:
      ensuite_shower:
        friendly_name: "Ensuite Shower"
        value_template: >- 
          {{ is_state('binary_sensor.ensuite_shower_above_humidity_threshold', 'on')
             and is_state('binary_sensor.ensuite_shower_humidity_falling', 'off') }}
        device_class: power #makes the icon yellow when on
        icon_template: mdi:shower-head

switch: 
  #The ensuite fan is shown as a light in Home Assistant - this converts it to a switch.
  - platform: template
    switches:
      ensuite_fan:
        value_template: "{{ is_state('light.ensuite_fan', 'on') }}"
        icon_template: >-
          {% if is_state('light.ensuite_fan', 'on') %}
          mdi:fan
          {% else %}
          mdi:fan-off
          {% endif %}
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.ensuite_fan
            brightness_pct: 100
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.ensuite_fan

var:
  master_bedroom_lights_brightness_control:
    initial_value: stop #allowed values: stop, dim, bright

automation:
  - alias: Master Bedroom - Turn Off Everything When Going To Bed
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_dimmer
          event: 1002 #single click
    action:
      - variables:
          #is the aircon already running in the master bedroom?
          aircon_initial_state: "{{ is_state('switch.aircon_on_off', 'on') and is_state('switch.aircon_zone_master', 'on') }}"
      - service: script.turn_off_whole_house 
      - service: light.turn_on
        entity_id: light.master_bedroom_ceiling
        data:
          brightness_pct: 5
      - delay:
          seconds: 20
      - service: light.turn_off
        entity_id: 
          - light.master_bedroom_ceiling
      #proceed to turn on the aircon in the master bedroom for 30 min if the aircon was already on in there
      - condition: template
        value_template: "{{ aircon_initial_state }}"
      - service: switch.turn_on
        entity_id: switch.aircon_on_off
      - delay:
          seconds: 5
      - service: switch.turn_on
        entity_id: switch.aircon_zone_master
      - delay:
          seconds: 10
      - service: input_number.set_value 
        data:
          entity_id: input_number.aircon_countdown_timer
          value: 30

  - alias: Master Bedroom - Toggle WIR Light
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_switch
          event: 1002 #single press
    action:
      - service: light.toggle
        entity_id: light.master_wir
        data_template:
          brightness_pct: '{% if now().hour >= 22 or now().hour < 4 %}20{% else %}100{% endif %}' #Dim light between 10pm-4am
  - alias: Ensuite - Turn On Fan When Shower Running
    trigger:
      platform: state
      entity_id: binary_sensor.ensuite_shower
      to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.ensuite_fan
  - alias: Ensuite - Turn Off Fan When Shower Stopped
    trigger:
      platform: state
      entity_id: binary_sensor.ensuite_shower
      to: 'off'
      for:
        minutes: 10
    action:
      - service: switch.turn_off
        entity_id: switch.ensuite_fan

#Automations to control the brightness of the master bedroom ceiling lights from a dimmer switch
  - alias: Master Bedroom Lights Brightness Control - Make Dim
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_dimmer
          event: 3001 #rotate left
    action:
      - service: var.set
        data:
          entity_id: var.master_bedroom_lights_brightness_control
          value: dim
  - alias: Master Bedroom Lights Brightness Control - Make Bright
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_dimmer
          event: 2001 #rotate right
    action:
      - service: var.set
        data:
          entity_id: var.master_bedroom_lights_brightness_control
          value: bright
  - alias: Master Bedroom Lights Brightness Control - Stop
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_dimmer
          event: 2003 #stop rotating right
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_dimmer
          event: 3003 #stop rotating left
    action:
      - service: var.set
        data:
          entity_id: var.master_bedroom_lights_brightness_control
          value: stop
  - alias: Master Bedroom Lights Brightness Control - Control Lights
    trigger:
      - platform: state
        entity_id: var.master_bedroom_lights_brightness_control
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: var.master_bedroom_lights_brightness_control
                state: "dim"
            sequence: 
              - repeat:
                  sequence:
                    - service: light.turn_on
                      entity_id: light.master_bedroom_ceiling
                      data:
                        brightness_step_pct: -10
                        transition: 0.2
                    - delay:
                        milliseconds: 200
                  until:
                    - condition: state
                      entity_id: var.master_bedroom_lights_brightness_control
                      state: "stop"
          - conditions:
              - condition: state
                entity_id: var.master_bedroom_lights_brightness_control
                state: "bright"
            sequence: 
              - repeat:
                  sequence:
                    - service: light.turn_on
                      entity_id: light.master_bedroom_ceiling
                      data:
                        brightness_step_pct: 10
                        transition: 0.2
                    - delay:
                        milliseconds: 200
                  until:
                    - condition: state
                      entity_id: var.master_bedroom_lights_brightness_control
                      state: "stop"
