binary_sensor:
  #If the humidity is high and not dropping quickly, the shower is on
  - platform: threshold
    name: Ensuite Shower Above Humidity Threshold
    entity_id: sensor.ensuite_shower_humidity
    upper: 92
  - platform: trend
    sensors:
      ensuite_shower_humidity_falling:
        entity_id: sensor.ensuite_shower_humidity
        sample_duration: 3600 #last 1 hour
        min_gradient: -0.002 #Humidity is dropping fast enough
        max_samples: 5
  - platform: template
    sensors:
      ensuite_shower:
        friendly_name: "Ensuite Shower"
        value_template: >-
          {{ is_state('binary_sensor.ensuite_shower_above_humidity_threshold', 'on')
             and is_state('binary_sensor.ensuite_shower_humidity_falling', 'off') }}
        device_class: power #makes the icon yellow when on
        icon_template: mdi:shower-head

switch:
  #The ensuite fan is shown as a light in Home Assistant - this converts it to a switch.
  - platform: template
    switches:
      ensuite_fan:
        value_template: "{{ is_state('light.ensuite_fan', 'on') }}"
        icon_template: >-
          {% if is_state('light.ensuite_fan', 'on') %}
          mdi:fan
          {% else %}
          mdi:fan-off
          {% endif %}
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.ensuite_fan
            brightness_pct: 100
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.ensuite_fan

var:
  master_bedroom_lights_brightness_control:
    initial_value: stop #allowed values: stop, dim, bright

automation:
  - alias: Master Bedroom - Turn Off Everything When Going To Bed
    id: master_bedroom_turn_off_everything_when_going_to_bed
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: master_door_switch
          event: 1002 #single click
    action:
      - variables:
          #is the aircon already running in the master bedroom?
          aircon_was_running_master_bedroom: "{{ states('climate.ac') != 'off' and is_state('switch.aircon_zone_master', 'on') }}"
          aircon_was_running_living_room: "{{ states('climate.ac') != 'off' and is_state('switch.aircon_zone_living', 'on') }}"
      - service: light.turn_off #start by turning off the brightest nearby lights
        entity_id:
          - light.master_wir
          - light.ensuite_light
      - service: light.turn_on #next turn the ceiling lights on dim to help navigate to bed
        entity_id: light.master_bedroom_ceiling
        data:
          brightness_pct: 5
      - delay:
          seconds: 20
      - service: script.turn_off_whole_house #after allowing time to get in to bed, turn off everything in the house
        data:
          excluded_lights: "['light.master_bedroom', 'light.master_bedroom_michael_lamp', 'light.master_bedroom_laura_lamp']" #Leave the bed side lamp and the corresponding hue group on if it already is
          turn_off_aircon: "{{ not aircon_was_running_master_bedroom }}"

      #proceed to turn on the aircon in the master bedroom for 60 min if the aircon was already on in there
      - condition: template
        value_template: "{{ aircon_was_running_master_bedroom or aircon_was_running_living_room }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.aircon_countdown_timer
          value: 60
      - delay:
          seconds: 3
      - service: switch.turn_off
        entity_id: switch.aircon_zone_theatre
      - delay:
          seconds: 3
      - service: switch.turn_off
        entity_id: switch.aircon_zone_bed23

  - alias: Master Bedroom - Toggle Michael Lamp Light
    id: master_bedroom_toggle_michael_lamp_light
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: master_bed_switch_2 #michael's button
          event: 1002 #single press
      - platform: event
        event_type: deconz_event
        event_data:
          id: master_door_switch #door button
          event: 5002 #right arrow
    action:
      - service: light.toggle
        entity_id: light.master_bedroom_michael_lamp
        data_template:
          brightness_pct: "{% if now().hour >= 22 or now().hour < 4 %}5{% else %}100{% endif %}" #Dim light between 10pm-4am

  - alias: Master Bedroom - Adjust Master Bedroom Light Brightness From Button Press
    id: master_bedroom_adjust_master_bedroom_light_brightness_from_button_press
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: master_door_switch #door button
          event: 2002 #bright
      - platform: event
        event_type: deconz_event
        event_data:
          id: master_door_switch #door button
          event: 3002 #dim
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.event == 2002 }}" #bright button pressed
            sequence:
              - service: light.turn_on
                entity_id: light.master_bedroom_ceiling
                data:
                  brightness_pct: 100
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.event == 3002 }}" #dim button pressed
            sequence:
              - service: light.turn_on
                entity_id: light.master_bedroom_ceiling
                data:
                  brightness_pct: 33

  - alias: Master Bedroom - Toggle Laura Lamp Light
    id: master_bedroom_toggle_laura_lamp_light
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: master_bed_switch_1 #laura's button
          event: 1002 #single press
      - platform: event
        event_type: deconz_event
        event_data:
          id: master_door_switch #door button
          event: 4002 #left arrow
    action:
      - service: light.toggle
        entity_id: light.master_bedroom_laura_lamp

  - alias: Master Bedroom - Turn On Walk-In-Robe Lights When Motion Detected
    id: master_bedroom_turn_on_wir_lights_when_motion_detected
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.wir_motion
          - binary_sensor.ensuite_motion
        to: "on"
    action:
      - choose: 
        #during the night
        - conditions:
          - condition: template
            value_template: '{{ now().hour >= 22 or now().hour <= 6 }}'
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.ensuite_led_strip #comes on at 10% automatically
        #during the day
        default:
          - service: light.turn_on
            target:
              entity_id: light.master_wir
            data:
              brightness_pct: 100
  
  - alias: Master Bedroom - Turn Off Walk-In-Robe Lights When No Motion Detected
    id: master_bedroom_turn_off_wir_lights_when_no_motion_detected
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.wir_motion
          - binary_sensor.ensuite_motion
        to: "off"
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.wir_motion
            state: "off"
          - condition: state
            entity_id: binary_sensor.ensuite_motion
            state: "off"
    action:
      - service: light.turn_off
        target:
          entity_id:
            - light.master_wir
            - light.ensuite_led_strip

  - alias: Ensuite - Turn On Fan When Shower Running
    id: ensuite_turn_on_fan_when_shower_running
    trigger:
      platform: state
      entity_id: binary_sensor.ensuite_shower
      to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.ensuite_fan

  - alias: Ensuite - Turn Off Fan When Shower Stopped
    id: ensuite_turn_off_fan_when_shower_stopped
    trigger:
      platform: state
      entity_id: binary_sensor.ensuite_shower
      to: "off"
      for:
        minutes: 10
    action:
      - service: switch.turn_off
        entity_id: switch.ensuite_fan
