binary_sensor:

  #If the humidity is high and not dropping quickly, the shower is on
  - platform: threshold
    name: Ensuite Shower Above Humidity Threshold
    entity_id: sensor.ensuite_shower_humidity
    upper: 90
  - platform: trend
    sensors:
      ensuite_shower_humidity_falling:
        entity_id: sensor.ensuite_shower_humidity
        sample_duration: 3600 #last 1 hour
        invert: true
        min_gradient: -0.002 #Humidity is dropping fast enough
  - platform: template
    sensors:
      ensuite_shower:
        friendly_name: "Ensuite Shower"
        value_template: >- 
          {{ is_state('binary_sensor.ensuite_shower_above_humidity_threshold', 'on')
             and is_state('binary_sensor.ensuite_shower_humidity_falling', 'on') }}
        device_class: power #makes the icon yellow when on
        icon_template: mdi:shower-head

automation:
  - alias: Master Bedroom - Turn Off Everything When Going To Bed
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_switch
          event: 1002
    action:
      - service: script.turn_off_whole_house 
      - service: light.turn_on
        entity_id: light.master_bedroom
        data:
          brightness_pct: 1
      - delay:
          seconds: 20
      - service: light.turn_off
        entity_id: 
          - light.master_bedroom
          - light.master_bedroom_lamp