binary_sensor:

  #If the humidity is high and not dropping quickly, the shower is on
  - platform: threshold
    name: Ensuite Shower Above Humidity Threshold
    entity_id: sensor.ensuite_shower_humidity
    upper: 92
  - platform: trend
    sensors:
      ensuite_shower_humidity_falling:
        entity_id: sensor.ensuite_shower_humidity
        sample_duration: 3600 #last 1 hour
        min_gradient: -0.002 #Humidity is dropping fast enough
        max_samples: 5
  - platform: template
    sensors:
      ensuite_shower:
        friendly_name: "Ensuite Shower"
        value_template: >- 
          {{ is_state('binary_sensor.ensuite_shower_above_humidity_threshold', 'on')
             and is_state('binary_sensor.ensuite_shower_humidity_falling', 'off') }}
        device_class: power #makes the icon yellow when on
        icon_template: mdi:shower-head

automation:
  - alias: Master Bedroom - Turn Off Everything When Going To Bed
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_switch
          event: 1004 #double press
    action:
      - service: script.turn_off_whole_house 
      - service: light.turn_on
        entity_id: light.master_bedroom_lamp
        data:
          brightness_pct: 1
      - delay:
          seconds: 20
      - service: light.turn_off
        entity_id: 
          - light.master_bedroom_lamp
  - alias: Master Bedroom - Toggle WIR Light
    trigger:
      - platform: event
        event_type: deconz_event
        event_data: 
          id: master_door_switch
          event: 1002 #single press
    action:
      - service: light.toggle
        entity_id: light.master_wir
        data_template:
          brightness_pct: '{% if now().hour >= 22 or now().hour < 4 %}20{% else %}100{% endif %}' #Dim light between 10pm-4am