automation:
  #Automation to transfer items from the Mealie shopping list to another list of your choice
  - id: mealie_transfer_shopping_list
    alias: "Mealie - Transfer Shopping List"
    description: "When shopping list items are added to the Mealie shopping list, transfer them to an alternative list."
    mode: queued
    max: 10
    initial_state: "on"
    variables:
      target_shopping_list: todo.groceries_list #CHANGEME: entity ID of your shopping list
      notify_service: notify.mobile_app_pixel_8_pro #CHANGEME: where to be notified if items fail to delete from Mealie shopping list
    trigger:
      - id: "regular_trigger"
        platform: state
        entity_id: todo.mealie_add_to_todoist
      - id: "fallback_trigger"
        platform: time_pattern
        minutes: "/10"
    condition:
      - condition: numeric_state
        entity_id: todo.mealie_add_to_todoist
        above: 0
    action:
      - alias: "Retrieve current list items"
        service: todo.get_items
        target:
          entity_id: todo.mealie_add_to_todoist
        data:
          status: 
            - needs_action
        response_variable: mealie_list_items
      - alias: "Add shopping list item to target list"
        service: todo.add_item
        target:
          entity_id: "{{ target_shopping_list }}"
        data:
          item: "{{ mealie_list_items['todo.mealie_add_to_todoist']['items'][0]['summary'] }}"
          description: Imported From Mealie

      - alias: "Delete shopping list item from Mealie"
        service: todo.remove_item
        target:
          entity_id: todo.mealie_add_to_todoist
        data:
          item: "{{ mealie_list_items['todo.mealie_add_to_todoist']['items'][0]['summary'] }}"
