scrape:
  - resource: "https://www.rba.gov.au/statistics/frequency/exchange-rates.html"
    scan_interval: 86400 #24 hours
    sensor:
      - name: "Exchange Rate - AUD to YEN - Today"
        unique_id: exchange_rate_aud_to_yen 
        select: "#JPY > td.highlight" 
        icon: "mdi:currency-jpy"
        device_class: "monetary"

yahoofinance:
  symbols: !secret stocks_to_track

sensor:
  - platform: statistics
    name: "Exchange Rate - AUD to YEN - Maximum Last 12 Months"
    unique_id: exchange_rate_aud_to_yen_maximum_last_12_months
    entity_id: sensor.exchange_rate_aud_to_yen
    state_characteristic: value_max
    max_age:
      hours: 8760 #1 year

automation:
  - alias: Money - Notify If New Maximum Annual Exchange Rate For Yen
    id: money_notify_if_new_maximum_exchange_rate_for_yen
    trigger:
      # Note: This will probably break in 1 year time, if the value of the yen drops
      # To properly handle this, it should only notify if maximum yen value goes up, not down
      # BUT probably won't need this by then, so not going to both with that right now.
      - platform: state
        entity_id: sensor.exchange_rate_aud_to_yen_maximum_last_12_months
    action:
      - alias: Send notification
        service: notify.pushbullet
        data:
          title: "Good News!"
          message: "The Yen has reached a new exchange rate yearly high! $1 AUD now buys {{ states('sensor.exchange_rate_aud_to_yen_maximum_last_12_months') }} yen. Click here for more details: https://g.co/kgs/q7Tb6YF"