script: 
  morning_alarms_if_today_is_special_play_music:
    alias: Morning Alarms - If Today Is Special Then Play Music
    variables: 
      date_today: >-
        {{  '%02d' % now().month }}-{{  '%02d' % now().day }}
    sequence:
      - choose:
        - conditions:
          - condition: template
            value_template: "{{ date_today == '09-21' }}"
          sequence:
            - service: media_player.volume_set
              data:
                entity_id: media_player.master_bedroom_speaker
                volume_level: 0.3
            - service: media_player.play_media
              data:
                entity_id: media_player.all_rooms
                media_content_id: '/local/sounds/september_21.mp3'
                media_content_type: 'audio/mp3'
  

automation:
  - alias: "Morning Alarms - September Twenty-First"
    id: morning_alarms_september_twenty_first
    mode: single
    trigger:
      - platform: time
        at: 
          - '08:00:00'
      - platform: zone
        entity_id: 
          - person.laura
          - person.michael
        zone: zone.home
        event: enter
    condition:
      - condition: template
        value_template:  >-
          {{ '%02d' % now().month + '-%02d' % now().day == '09-21' }}
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "off" #don't run if on holiday
    action:
      - delay:
          minutes: 5
      - service: script.morning_alarms_if_today_is_special_play_music 