binary_sensor:
  - platform: ping
    host: !secret device_michael_pc_ip_address
    name: Michael PC
    count: 2
    scan_interval: 5
  - platform: ping
    host: !secret device_laura_pc_ip_address
    name: Laura PC
    count: 2
    scan_interval: 5
  - platform: ping
    host: !secret device_michael_work_laptop_ip_address
    name: Michael Work Laptop
    count: 2
    scan_interval: 5
  - platform: ping
    host: !secret device_laura_work_laptop_ip_address
    name: Laura Work Laptop
    count: 2
    scan_interval: 5
  - platform: group
    name: Michael In Meeting
    entities:
      - binary_sensor.michael_desktop_in_meeting
      - binary_sensor.michael_work_in_meeting 

automation:
  - alias: Front Hall - Turn On Hallway Light If PC Turned Off At Night
    id: front_hall_turn_on_hallway_light_if_pc_turned_off_at_night
    trigger:
      platform: state
      entity_id: binary_sensor.michael_pc
      to: "off"
      from: "on"
    condition:
      condition: state  # from sunset until sunrise
      entity_id: sun.sun
      state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id:
          - light.entry_hall_lights
      - delay:
          minutes: 5
      - service: light.turn_off
        entity_id:
          - light.entry_hall_lights

  - alias: Office - When Black Ink Low, Add To List
    id: office_when_black_ink_low_add_to_list
    trigger:
      platform: numeric_state
      entity_id: sensor.canon_ts3300_series_black
      below: 20
    condition:
      - condition: template #Only add it to the shopping list once
        value_template: "{{ 'Black ink (PG-645 or PG-645XL)' not in state_attr('calendar.groceries_list', 'all_tasks') }}"
    action:
      - service: todoist.new_task
        data:
          content: Black ink (PG-645 or PG-645XL)
          project: Groceries List
      - service: script.chatgpt_reword_message
        data:
          prompt: "Black printer ink is running low and has been added to your shopping list."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "{{ chatgpt_response.text }}"

  - alias: Office - When Colour Ink Low, Add To List
    id: office_when_colour_ink_low_add_to_list
    trigger:
      platform: numeric_state
      entity_id: sensor.canon_ts3300_series_color
      below: 20
    condition:
      - condition: template #Only add it to the shopping list once
        value_template: "{{ 'Colour ink (PG-646 or PG-646XL)' not in state_attr('calendar.groceries_list', 'all_tasks') }}"
    action:
      - service: todoist.new_task
        data:
          content: Colour ink (PG-646 or PG-646XL)
          project: Groceries List
      - service: script.chatgpt_reword_message
        data:
          prompt: "Colour printer ink is running low and has been added to your shopping list."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "{{ chatgpt_response.text }}"

  - alias: Office - Toggle Lamp With Laura's Switch
    id: office_toggle_lamp_with_laura_switch
    trigger: 
      - platform: event
        event_type: zha_event
        event_data: 
          device_ieee: !secret zha_laura_office_lights_switch
          command: "single"
    action:
      - choose:
        # If lamp is off, turn it on
          - conditions:
              - condition: state
                entity_id: light.office_lamp
                state: "off"
            sequence: 
              - service: light.turn_on
                target:
                  entity_id: light.office_lamp
                data:
                  brightness: 160
                  color_temp: 400
        # Otherwise turn off the lamp
        default:
          - service: light.turn_off
            entity_id: light.office_lamp

  - alias: Office - Turn On Lamp When Michael Is In A Meeting
    id: office_turn_on_lamp_when_michael_is_in_a_meeting
    trigger: 
      - platform: state
        entity_id: binary_sensor.michael_in_meeting
        to: "on"
    action:
      - service: scene.create
        data:
          scene_id: office_lamp_original_state
          snapshot_entities:
            - light.office_lamp
      - service: light.turn_on
        target:
          entity_id: light.office_lamp
        data:
          brightness_pct: 1
          color_name: "red"
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.michael_in_meeting
            to: "off"
      - service: scene.turn_on
        entity_id: scene.office_lamp_original_state

  - alias: Office - Blinds Open In The Morning
    id: office_blinds_open_in_the_morning
    trigger: 
      - platform: time
        at: "08:30:00"
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: "disarmed"
    action:
      - service: number.set_value
        data:
          value: 100 #fully open
        target:
          entity_id: number.office_blinds_height_pct

  - alias: Office - Blinds Mid At Lunch Time
    id: office_blinds_mid_at_lunch_time
    trigger: 
      - platform: time
        at: "12:30:00"
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: "disarmed"
    action:
      - service: number.set_value
        data:
          value: 35 #where the metal bar is
        target:
          entity_id: number.office_blinds_height_pct

  - alias: Office - Blinds Close When Required
    id: office_blinds_close_when_required
    trigger: 
      - platform: state
        entity_id: 
          - alarm_control_panel.alarm_com
        to:
          - "armed_home"
          - "armed_away"
      - platform: time
        at: "23:30:00"
    action:
      - service: number.set_value
        data:
          value: 18 #as closed as can go without hitting the dog bed
        target:
          entity_id: number.office_blinds_height_pct

  - alias: Office - Blinds Open When Arriving Home
    id: office_blinds_open_when_arriving_home
    trigger: 
      - platform: state
        entity_id: 
          - alarm_control_panel.alarm_com
        to: "disarmed"
    action:
      - choose:
          - conditions:
              - condition: time
                after: "23:30:00"
                before: "08:30:00"
            sequence:
            - service: number.set_value
              data:
                value: 18 #as closed as can go without hitting the dog bed
              target:
                entity_id: number.office_blinds_height_pct
          - conditions:
              - condition: time
                after: "08:30:00"
                before: "12:30:00"
            sequence:
            - service: number.set_value
              data:
                value: 100 #fully open
              target:
                entity_id: number.office_blinds_height_pct
          - conditions:
              - condition: time
                after: "12:30:00"
                before: "23:30:00"
            sequence:
            - service: number.set_value
              data:
                value: 35 #where the metal bar is
              target:
                entity_id: number.office_blinds_height_pct

  - alias: Office - Mute Office Speakers When Michael Is In A Meeting
    id: office_mute_office_speakers_when_michael_is_in_a_meeting
    trigger: 
      - platform: state
        entity_id: binary_sensor.michael_in_meeting
        to: "on"
    action:
      - service: media_player.volume_mute
        data:
          is_volume_muted: true
        target:
          entity_id: 
            - media_player.office_google_home
            - media_player.office_pc_speakers
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.michael_in_meeting
            to: "off"
      - service: media_player.volume_mute
        data:
          is_volume_muted: false
        target:
          entity_id: 
            - media_player.office_google_home
            - media_player.office_pc_speakers

  - alias: Office - Mute Office Speaker When Laura Is In A Meeting
    id: office_mute_office_speaker_when_laura_is_in_a_meeting
    mode: restart
    trigger:
      - platform: event
        event_type: zha_event
        event_data: 
          device_ieee: !secret zha_laura_office_aircon_button
          #command: "on"
    action:
      - service: media_player.volume_mute
        data:
          is_volume_muted: true
        target:
          entity_id: 
            - media_player.office_google_home
            - media_player.office_pc_speakers
      - choose:
          - conditions:
              - "{{ trigger.event.data.command == 'off' }}"
            sequence:
              - delay:
                  minutes: 30
          - conditions:
              - "{{ trigger.event.data.command == 'on' }}"
            sequence:
              - delay:
                  minutes: 60
      - service: media_player.volume_mute
        data:
          is_volume_muted: false
        target:
          entity_id: 
            - media_player.office_google_home
            - media_player.office_pc_speakers

  - alias: Office - Turn On Light When Motion Detected
    id: office_turn_on_light_when_motion_detected
    mode: restart
    trigger:
      # motion detected
      - platform: state
        entity_id: binary_sensor.office_presence_sensor_moving_target
        to: "on"
        from: "off"
    condition:
      # only run if lights are off
      - condition: state
        entity_id: 
          - light.office_ceiling
          - light.office_lamp
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: state #from sunset until sunrise
                entity_id: sun.sun
                state: "below_horizon"
            sequence:
              - service: light.turn_on
                data:
                  color_temp: 350
                  brightness_pct: 30
                target:
                  entity_id: light.office_lamp
        default:
          - service: light.turn_on
            target:
              entity_id: light.office_ceiling

  - alias: Office - Turn Off Lights When No Presence Detected
    id: office_turn_off_light_when_no_presence_detected
    mode: restart
    trigger:
      # no presence detected for 5 mintues
      - platform: state
        entity_id: binary_sensor.office_presence_sensor_presence
        to: "off"
        for:
          minutes: 5
    condition:
      # only run if lights are in the state set by the "turn" on automation 
      # (ie. not coloured with a notification), or if they are off
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: light.office_lamp
                attribute: color_mode
                state: "color_temp"
              - condition: state
                entity_id: light.office_lamp
                attribute: color_temp
                state: 350
          - condition: state
            entity_id: light.office_lamp
            state: "off"
    action:
      - service: light.turn_off
        target:
          entity_id:
            - light.office_ceiling
            - light.office_lamp

script:
  flash_office_lamp:
    fields:
      colour:
        description: "What colour to flash the lamp"
        example: "green"
    sequence:
      - service: light.turn_on
        target:
          entity_id: light.office_lamp
        data:
          brightness_pct: 50
          color_name: "{{colour}}"
      - delay:
          seconds: 1
      - choose:
          #if in meeting, return the light to a red colour
          - conditions:
              - condition: state
                entity_id: binary_sensor.michael_in_meeting
                state: "on"
            sequence: 
              - service: light.turn_on
                target:
                  entity_id: light.office_lamp
                data:
                  brightness_pct: 1
                  color_name: "red"
        #if not in a meeting, turn the light off
        default:
          - service: light.turn_off
            entity_id: light.office_lamp