homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0

ios:
  
# Push Notifications  
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

zone:
  - name: Michael's Work
    latitude: !secret zone_michael_work_latitude
    longitude: !secret zone_michael_work_longitude
    radius: 120
    icon: mdi:briefcase

  # This will override the default home zone
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 220
    icon: mdi:home

automation:
  # - alias: Location - Notify Michael If Laura Leaving Work
  #   trigger:
  #     platform: zone
  #     entity_id: device_tracker.lauras_iphone
  #     zone: zone.laura_s_work
  #     event: leave
  #   action:
  #     - service: notify.pushbullet
  #       data:
  #         message: Laura is leaving work.

  #Notify when someone comes homes
  - alias: Location - Notify When Someone Comes Home
    initial_state: false
    trigger:
      - platform: state
        entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
        to: "open"
      - platform: state
        entity_id: sensor.front_door
        to: "Open"
      - platform: state
        entity_id: binary_sensor.garage_door_internal
        to: "on"
    action:
      - service: notify.pushbullet
        data:
          message: Someone has come home.
      - service: automation.turn_off
        entity_id:
          - automation.location_notify_when_someone_comes_home

person:
  - name: Michael
    id: michael
    user_id: 0e77a256b08c47f7989413c4599cc865
    device_trackers:
      - device_tracker.michael_galaxy_s10
      - device_tracker.phone_ping_michael
  - name: Laura
    id: laura
    user_id: c93d4309ba8141eabe4a306b2fb5ecc7
    device_trackers:
      - device_tracker.phone_ping_laura
    

device_tracker:
  - platform: ping
    hosts:
      phone_ping_michael: !secret device_michael_phone_ip_address
  - platform: ping
    hosts:
      phone_ping_laura: !secret device_laura_phone_ip_address
    consider_home: 600
  - platform: bluetooth_le_tracker
    track_new_devices: false
