homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0

input_boolean:
  holiday_mode:
    name: Holiday Mode
    icon: mdi:palm-tree
  michael_is_driving_home:
    name: Michael Is Driving Home
    icon: "mdi:car"
    initial: false

ios:

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 220
    icon: mdi:home

  - name: Capel House
    latitude: !secret zone_capel_house_latitude
    longitude: !secret zone_capel_house_longitude
    radius: 100
    icon: mdi:home

  - name: Laura's Work
    latitude: !secret zone_laura_work_latitude
    longitude: !secret zone_laura_work_longitude
    radius: 220
    icon: mdi:briefcase

  - name: Local Train Station
    latitude: !secret zone_local_train_station_latitude
    longitude: !secret zone_local_train_station_longitude
    radius: 200
    icon: mdi:train

  - name: Crown Perth
    latitude: -31.9597198
    longitude: 115.8943751
    radius: 400
    icon: mdi:dice-6

automation:
  - alias: Location - Open Garage Door When Driving Home
    id: location_open_garage_door_when_driving_home
    trigger:
      - platform: zone
        entity_id: person.michael
        zone: zone.home
        event: enter
    condition: 
      - condition: state
        entity_id: binary_sensor.pixel_8_pro_android_auto #Michael is in the car
        state: "on"
    action:
      - action: cover.open_cover
        target:
          entity_id: cover.garage_door
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.michael_is_driving_home
      #Temporary notification as well, so I'm aware it has been done
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "The garage door was opened since you arrived home."
          data:
            notification_icon: mdi:garage-open-variant
      

  - alias: Location - Turn Off Aircon When On Holiday
    id: location_turn_off_aircon_when_on_holiday
    trigger:
      - platform: state
        entity_id: climate.ac
        from: "off"
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    action:
      - service: climate.turn_off
        target:
          entity_id: climate.ac

  - alias: Location - Turn On Presence Simulation At Night When On Holiday
    id: location_turn_on_presence_simulation_when_on_holiday
    trigger:
      - id: "sunset"
        platform: sun
        event: sunset
      - id: "sunrise"
        platform: sun
        event: sunrise
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    action:
      - service: "{{ 'switch.turn_on' if trigger.id == 'sunset' else 'switch.turn_off' }}"
        target:
          entity_id: switch.holiday_mode_presence_simulation

  - alias: Location - Turn Off Presence Simulation When Holiday Mode Deactivated
    id: location_turn_off_presence_simulation_when_holiday_mode_deactivated
    trigger:
      - platform: state
        entity_id: input_boolean.holiday_mode
        to: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.holiday_mode_presence_simulation

  - alias: Location - Remind Me To Turn Off Holiday Mode When Arriving Home
    id: location_remind_me_to_turn_off_holiday_mode_when_arriving_home
    trigger:
      - platform: zone
        entity_id: person.michael
        zone: zone.home
        event: enter
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    action:
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "Welcome home! Don't forget to disable Holiday Mode."
          data:
            notification_icon: "mdi:caravan"

  - alias: Location - Notify Michael If Laura Leaving Work
    id: location_notify_michael_if_laura_leaving_work
    trigger:
      platform: zone
      entity_id: device_tracker.lauras_iphone
      zone: zone.laura_s_work
      event: leave
    condition:
      - condition: time
        after: "16:00:00"
        before: "19:00:00"
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "Laura is leaving work."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_pixel_8_pro
        data:
          title: "Laura leaving work"
          message: "{{ chatgpt_response.text }}"
          data:
            notification_icon: "mdi:face-woman"

  #Notify when someone comes homes
  - alias: Location - Notify When Someone Comes Home
    id: location_notify_when_someone_comes_home
    initial_state: false
    trigger:
      - platform: state
        entity_id: cover.garage_door
        to: "open"
      - platform: state
        entity_id: sensor.alarmdotcom_front_door
        to: "Open"
      - platform: state
        entity_id:
          - binary_sensor.garage_door_internal
          - binary_sensor.front_door
        to: "on"
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "Someone has come home."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_pixel_8_pro
        data:
          title: "Someone has come home"
          message: "{{ chatgpt_response.text }}"
          data:
            notification_icon: "mdi:door"
      - service: automation.turn_off
        entity_id:
          - automation.location_notify_when_someone_comes_home

  - alias: Location - Remind Michael To Pay For Train Parking
    id: location_remind_michael_to_pay_for_train_parking
    mode: single
    trigger:
      - platform: state
        entity_id:
          - sensor.pixel_8_pro_bluetooth_connection
    variables:
      mazda_mac_address: !secret mazda_bluetooth_mac_address
    condition:
      - alias: "Check whether the Mazda was just disconnected"
        condition: template
        value_template: >
          {{ 
            mazda_mac_address not in state_attr('sensor.pixel_8_pro_bluetooth_connection', 'connected_paired_devices')
            and mazda_mac_address in trigger.from_state.attributes['connected_paired_devices']
          }}
      - alias: "Check whether Michael is at the train station"
        condition: zone
        entity_id: person.michael
        zone: zone.local_train_station
    action:
      - delay:
          minutes: 2
      - service: script.chatgpt_reword_message
        data:
          prompt: "Don't forget to pay for parking! "
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_pixel_8_pro
        data:
          title: "Parking Payment Reminder"
          message: "{{ chatgpt_response.text }}"
          data:
            color: "#FFA000"
            ttl: 0
            priority: high
            notification_icon: "mdi:car"

  - alias: Location - Remind Laura To Pay For Train Parking
    id: location_remind_laura_to_pay_for_train_parking
    mode: single
    trigger:
      platform: state
      entity_id: person.laura
      to: "Local Train Station"
      for:
        minutes: 1
        seconds: 30
    condition:
      - condition: time
        before: "15:00:00"
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "Don't forget to pay for parking!"
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_lauras_iphone
        data:
          message: "{{ chatgpt_response.text }}"

  - alias: Location - Remind Laura Not To Leave Lunch At Work
    id: location_remind_laura_not_to_leave_lunch_at_work
    mode: single #prevents reminding multiple times too quickly
    trigger:
      - platform: zone
        entity_id: device_tracker.lauras_iphone
        zone: zone.laura_s_work
        event: leave
      - platform: state
        entity_id: sensor.lauras_iphone_ssid
        from: "BYOD"
    condition:
      - condition: time
        after: "15:00:00"
        before: "19:00:00"
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "Don't forget to remove your lunch from the work fridge!"
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_lauras_iphone
        data:
          message: "{{ chatgpt_response.text }}"
      - delay:
          minutes: 15 #prevents reminding multiple times too quickly

  - alias: Location - Remind Me To Bring My Crown Rewards Card
    id: location_remind_me_to_bring_my_crown_rewards_card
    trigger:
      #Check 8 hours and 1 hour before each event in either calendar.
      - platform: calendar
        event: start
        entity_id: calendar.laura_mickey
        offset: "-08:00:00"
      - platform: calendar
        event: start
        entity_id: calendar.laura_mickey
        offset: "-01:00:00"
      - platform: calendar
        event: start
        entity_id: calendar.personal
        offset: "-08:00:00"
      - platform: calendar
        event: start
        entity_id: calendar.personal
        offset: "-01:00:00"
    condition:
      #If the event contains Crown Perth or Crown Metropol Perth in the location
      - condition: template
        value_template: '{{ trigger.calendar_event.location is search(".*Crown (Metropol )?Perth.*", ignorecase=True) }}'
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "Don't forget your 'Crown Rewards Card'. You may need it when you go to {{trigger.calendar_event.summary}}."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_pixel_8_pro
        data:
          title: "Remember Your Crown Rewards Card"
          message: "{{ chatgpt_response.text }}"
          data:
            group: "Crown Rewards"
            notification_icon: "mdi:crown-circle"
         
  - alias: Location - Turn Off House Nobody Is Home
    id: location_turn_off_house_when_nobody_is_home
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_home
        from: 'on'
        to: 'off'
        for:
          minutes: 2
    action:
      - service: script.turn_off_whole_house
        data: 
          excluded_lights: "['light.garage', 'light.garage_light', 'light.front_porch_light']" #Leave these lights on if they're already on
          turn_off_aircon: "true"
      - service: climate.turn_off
        entity_id: climate.ac
      #TEMPORARY: Notify Michael this has occurred
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "The house was turned off because nobody was home."
          data:
            notification_icon: mdi:home
        
  - alias: Location - Alert If Doors Left Open
    id: location_alert_if_doors_left_open
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_home
        from: 'on'
        to: 'off'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.back_door_glass
          state: 'on'
        - condition: state
          entity_id: binary_sensor.laundry_door
          state: 'on'
        - condition: state
          entity_id: bindary_sensor.front_door
          state: 'on'
    action:
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: A door was left open while nobody is home.
          data:
            notification_icon: "mdi:shield-home"
      - service: notify.mobile_app_lauras_iphone
        data:
          message: A door was left open while nobody is home.

person:
  - name: Michael
    id: michael
    user_id: 0e77a256b08c47f7989413c4599cc865
    device_trackers:
      - device_tracker.google_pixel_watch
      - device_tracker.michael_pixel_8_pro
  - name: Laura
    id: laura
    user_id: c93d4309ba8141eabe4a306b2fb5ecc7
    device_trackers:
      - device_tracker.lauras_iphone
      - device_tracker.phone_ping_laura

binary_sensor:
  - platform: template
    sensors:
      someone_home:
        friendly_name: Someone Home
        icon_template: >-
          {% if is_state('binary_sensor.someone_home','on') %} mdi:home-account
          {% else %} mdi:home-outline
          {% endif %}
        value_template: "{{ is_state('person.michael','home') or  is_state('person.laura','home') }}"