homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0

ios:
  
# Push Notifications  
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

zone:
  - name: Michael's Work
    latitude: !secret zone_michael_work_latitude
    longitude: !secret zone_michael_work_longitude
    radius: 100
    icon: mdi:briefcase

  # This will override the default home zone
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 220
    icon: mdi:home

  - name: Capel House
    latitude: !secret zone_capel_house_latitude
    longitude: !secret zone_capel_house_longitude
    radius: 100
    icon: mdi:home

  - name: Laura's Work
    latitude: !secret zone_laura_work_latitude
    longitude: !secret zone_laura_work_longitude
    radius: 220
    icon: mdi:store

  - name: Greg's House
    latitude: !secret zone_greg_house_latitude
    longitude: !secret zone_greg_house_longitude
    radius: 125
    icon: mdi:office-building

  - name: University
    latitude: !secret zone_university_latitude
    longitude: !secret zone_university_longitude
    radius: 900
    icon: mdi:school

automation:
  # - alias: Location - Notify Michael If Laura Leaving Work
  #   id: location_notify_michael_if_laura_leaving_work
  #   trigger:
  #     platform: zone
  #     entity_id: device_tracker.lauras_iphone
  #     zone: zone.laura_s_work
  #     event: leave
  #   action:
  #     - service: notify.mobile_app_michael_s_galaxy_s10
  #       data:
  #         message: Laura is leaving work.

  #Notify when someone comes homes
  - alias: Location - Notify When Someone Comes Home
    id: location_notify_when_someone_comes_home
    initial_state: false
    trigger:
      - platform: state
        entity_id: cover.garage_door
        to: "open"
      - platform: state
        entity_id: sensor.alarmdotcom_front_door
        to: "Open"
      - platform: state
        entity_id: 
          - binary_sensor.garage_door_internal
          - binary_sensor.front_door
        to: "on"
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: Someone has come home.
      - service: automation.turn_off
        entity_id:
          - automation.location_notify_when_someone_comes_home

  - alias: Location - Notify Michael When Leaving Home Without Laptop
    id: location_notify_michael_when_leaving_home_without_laptop
    trigger:
      - platform: zone
        entity_id: person.michael
        zone: zone.home
        event: leave
    condition:
      #TODO: Work out if today is a work day based on my calendar? Or Workday Binary Sensor.
      - condition: time
        after: "06:00:00"
        before: "09:00:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: binary_sensor.michael_work_laptop
        state:  "on" #Laptop is still plugged in to desk
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: Did you forget to bring your work laptop with you?

  - alias: Location - Fade Lights On When Arriving Home After Dark
    id: location_fade_lights_on_when_disarming_after_dark
    mode: single
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.front_door
          - binary_sensor.garage_door_internal
        from: "off"
        to: "on"
    condition:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: 'armed_away'
        for:
          minutes: 5
    action:
      - service: light.turn_on
        entity_id:
        - light.kitchen_island
        data:
          transition: 60

person:
  - name: Michael
    id: michael
    user_id: 0e77a256b08c47f7989413c4599cc865
    device_trackers:
      - device_tracker.michael_galaxy_s10
      - device_tracker.phone_ping_michael
  - name: Laura
    id: laura
    user_id: c93d4309ba8141eabe4a306b2fb5ecc7
    device_trackers:
      - device_tracker.lauras_iphone
      - device_tracker.phone_ping_laura
    
device_tracker:
  - platform: ping
    hosts:
      phone_ping_laura: !secret device_laura_phone_ip_address
    consider_home: 0:20 
  - platform: ping
    hosts:
      phone_ping_michael: !secret device_michael_phone_ip_address
