automation:
  - alias: Living Room - Notify Me If Dog Door Is Used
    id: living_room_notify_me_if_dog_door_is_used
    trigger:
      - platform: state
        entity_id: binary_sensor.dog_door
        from: 'off'
        to: 'on'
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: The dog door was used!
          data:
            group: Dog Door
            tag: dog_door
            color: 'green'
            ttl: 0
      - delay:
          minutes: 1

  # - alias: Living Room - Turn On Flood Lights If Dog Door Is Used
  #   id: living_room_turn_on_flood_lights_if_dog_door_is_used
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.dog_door
  #       from: 'off'
  #       to: 'on'
  #   condition:
  #     - condition: state #from sunset until sunrise
  #       entity_id: sun.sun
  #       state: "below_horizon"
  #   action:
  #     - service: scene.create
  #       data:
  #         scene_id: flood_lights_state
  #         snapshot_entities: light.garden_flood_lights
  #     - service: light.turn_on
  #       target:
  #         entity_id: light.garden_flood_lights
  #     - delay:
  #         minutes: 5
  #     - service: scene.turn_on
  #       target:
  #         entity_id: scene.flood_lights_state

  - alias: Pets - Toggle Living Room Lights
    id: pets_toggle_living_room_lights
    trigger: 
      - platform: event
        event_type: deconz_event
        event_data: 
          id: artemis_light_switch
          event: 1002 #short press
      - platform: event
        event_type: deconz_event
        event_data: 
          id: artemis_light_switch
          event: 1001 #long press
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: Artemis pushed the lights button! 
      - choose:
        # If living room light is off, turn it on
          - conditions:
              - condition: state
                entity_id: light.living_room
                state: "off"
            sequence: 
              - service: light.turn_on
                target:
                  entity_id: light.living_room
        # Otherwise turn off all the central living lights
        default:
          - service: light.turn_off
            entity_id: 
              - light.living_room
              - light.dining_room
              - light.kitchen_lights

  - alias: Pets - Pretend To Ring Doorbell
    id: pets_pretend_to_ring_doorbell
    trigger: 
      - platform: time
        at: 
          - '09:58:00'
          - '11:58:00'
          - '14:58:00'
          - '17:58:00'
    action:
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "This is a fake doorbell to desensitise the dog."
          data:
            group: "Doggy Doorbell"
      - service: notify.mobile_app_lauras_iphone
        data:
          message: "This is a fake doorbell to desensitise the dog."
      - service: media_player.play_media
        data:
          entity_id: media_player.central_living_speakers
          media_content_id: '/local/doorbell.mp3'
          media_content_type: 'audio/mp3'
