plant:
  alfresco_fig:
    sensors:
      moisture: sensor.fig_moisture
      battery: sensor.fig_battery
      temperature: sensor.fig_temperature
      conductivity: sensor.fig_conductivity
      brightness: sensor.fig_light
 
    #Monstera-specific values from the MiFlora app
    # min_moisture: 15
    # max_moisture: 60
    # min_conductivity: 350
    # max_conductivity: 2000
    # min_temperature: 12
    # max_temperature: 32
    # min_brightness: 800
    # max_brightness: 15000

    #Mint-specific values from the MiFlora app
    # min_moisture: 15
    # max_moisture: 60
    # min_conductivity: 350
    # max_conductivity: 2000
    # min_temperature: 8
    # max_temperature: 32
    # min_brightness: 3000
    # max_brightness: 60000

    #Fig-specific values from the MiFlora app
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 5
    max_temperature: 35
    min_brightness: 3500
    max_brightness: 60000

alert:
  plant_watering_reminder:
    name: "The fig tree needs attention"
    title: "The fig tree needs attention"
    message: "Problem: {{ state_attr('plant.alfresco_fig', 'problem') }}"
    entity_id: plant.alfresco_fig
    state: 'problem'
    repeat: 1440 #24 hours
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_lauras_iphone
      - mobile_app_michael_s_galaxy_s10
    data:
      group: MiFlora
