input_boolean:
  washing_machine_notify_michael:
    name: Washing Machine - Notify Michael
    icon: mdi:bell-ring
  washing_machine_notify_laura:
    name: Washing Machine - Notify Laura
    icon: mdi:bell-ring

binary_sensor:
  - platform: template
    sensors:
      #If the machine needs emptying and Michael toggle is on, start notifications
      washing_machine_notifications_michael:
        friendly_name: "Washing Machine Notifications Will Be Triggering For Michael"
        value_template: >-
          {{
            is_state('binary_sensor.washing_machine_needs_emptying', 'on')
            and is_state('input_boolean.washing_machine_notify_michael', 'on')
          }}
      #If the machine needs emptying and Laura toggle is on, start notifications
      washing_machine_notifications_laura:
        friendly_name: "Washing Machine Notifications Will Be Triggering For Laura"
        value_template: >-
          {{
            is_state('binary_sensor.washing_machine_needs_emptying', 'on')
            and is_state('input_boolean.washing_machine_notify_laura', 'on')
          }}

automation:

  - alias: Washing Machine - Disable Notifications When Washing Machine Emptied
    id: washing_machine_disable_notifications_when_washing_machine_emptied
    trigger:
      #disabled when washing machine door is opened
      - platform: state
        entity_id: binary_sensor.washing_machine_door
        from: 'off'
        to: 'on' 
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: 
            - input_boolean.washing_machine_notify_laura
            - input_boolean.washing_machine_notify_michael

  - alias: Washing Machine - Turn On Washing Machine Notifications For Michael
    id: washing_machine_turn_on_washing_machine_notifications_for_michael
    trigger:
      - platform: event
        event_type: zha_event
        event_data: 
          device_ieee: !secret zha_washing_machine_notifications_switch
          command: "on" #michael
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.washing_machine_notify_michael
      - service: script.chatgpt_reword_message
        data:
          prompt: "Washing machine notifications switched on for Michael."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_pixel_8_pro
        data:
          title: "Notifications Turned On"
          message: "{{ chatgpt_response.text }}"
          data:
            timeout: 60
            notification_icon: "mdi:washing-machine"

  - alias: Washing Machine - Turn On Washing Machine Notifications For Laura
    id: washing_machine_turn_on_washing_machine_notifications_for_laura
    trigger:
      - platform: event
        event_type: zha_event
        event_data: 
          device_ieee: !secret zha_washing_machine_notifications_switch
          command: "off" #laura
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.washing_machine_notify_laura

  - alias: Washing Machine - Pause Washing Machine Notifications Until Home
    id: washing_machine_pause_washing_machine_notifications_until_home
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: mute_washing_machine_notifications_until_home
    condition:
      - condition: state
        entity_id: person.michael
        state: 'not_home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.washing_machine_notify_michael
      - wait_template: "{{ is_state('person.michael', 'home') }}"
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.washing_machine_notify_michael

  - alias: Washing Machine - Pause Washing Machine Notifications Until Morning
    id: washing_machine_pause_washing_machine_notifications_until_morning
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: mute_washing_machine_notifications_until_morning
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.washing_machine_notify_michael
      - wait_template: "{{ now().hour == 7 }}" #Restart notifications at 7am 
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.washing_machine_notify_michael

alert:
  washing_machine_reminder_michael:
    name: The washing machine has finished.
    entity_id: binary_sensor.washing_machine_notifications_michael
    state: 'on'
    repeat: 60
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_pixel_8_pro
    data:
      group: Washing Machine
      notification_icon: "mdi:washing-machine"
      actions:
        - action: "mute_washing_machine_notifications_until_home"
          title: "Mute Until I'm Home"
        - action: "mute_washing_machine_notifications_until_morning"
          title: "Mute Until Morning"
  washing_machine_reminder_laura:
    name: The washing machine has finished.
    entity_id: binary_sensor.washing_machine_notifications_laura
    state: 'on'
    repeat: 60
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_lauras_iphone
