input_boolean:
  medicine_reminder_michael_toggle:
    name: Remind Michael To Take Medicine
    icon: mdi:pill
    initial: false
  medicine_reminder_laura_toggle:
    name: Remind Laura To Take Medicine
    icon: mdi:pill
    initial: false

automation:
  - alias: Medicine - Activate Michael Reminder When Medicine Needs Taking
    id: medicine_activate_michael_reminder_when_medicine_needs_taking
    trigger:
      - platform: time
        at: 
          - '07:00:00'
          - '19:00:00'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.medicine_reminder_michael_toggle

  - alias: Medicine - Activate Laura Reminder When Medicine Needs Taking
    id: medicine_activate_laura_reminder_when_medicine_needs_taking
    trigger:
      - platform: time
        at: 
          - '20:30:00'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.medicine_reminder_laura_toggle

  - alias: Medicine - Deactivate Michael Reminder Once Medicine Is Taken
    id: medicine_deactivate_michael_reminder_once_medicine_is_taken
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: medicine_reminder_michael_finished
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.medicine_reminder_michael_toggle
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "clear_notification"
          data:
            tag: "medicine-reminders"

  - alias: Medicine - Deactivate Laura Reminder Once Medicine Is Taken
    id: medicine_deactivate_laura_reminder_once_medicine_is_taken
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: medicine_reminder_laura_finished
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.medicine_reminder_laura_toggle

  - alias: Medicine - Pause Michael Medicine Notifications Until Home
    id: medicine_pause_michael_medicine_notifications_until_home
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: medicine_reminder_michael_mute_until_home
    condition:
      - condition: state
        entity_id: person.michael
        state: 'not_home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.medicine_reminder_michael_toggle
      - wait_template: "{{ is_state('person.michael', 'home') }}"
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.medicine_reminder_michael_toggle

  - alias: Medicine - Pause Laura Medicine Notifications Until Home
    id: medicine_pause_laura_medicine_notifications_until_home
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: medicine_laura_reminder_mute_until_home
    condition:
      - condition: state
        entity_id: person.laura
        state: 'not_home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.medicine_reminder_laura_toggle
      - wait_template: "{{ is_state('person.laura', 'home') }}"
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.medicine_reminder_laura_toggle

alert:
  medicine_reminder_michael:
    name: Remember to take your medicine.
    entity_id: input_boolean.medicine_reminder_michael_toggle
    state: 'on'
    repeat: 15
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_pixel_8_pro
    data:
      group: Medicine
      tag: medicine-reminders
      notification_icon: "mdi:pill"
      actions:
        - action: "medicine_reminder_michael_finished" 
          title: "I've Taken It"
        - action: "medicine_reminder_michael_mute_until_home" 
          title: "Mute Until I'm Home"
  medicine_reminder_laura:
    name: Remember to take your medicine.
    entity_id: input_boolean.medicine_reminder_laura_toggle
    state: 'on'
    repeat: 15
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_lauras_iphone
    data:
      group: Medicine
      actions:
        - action: "medicine_reminder_laura_finished" 
          title: "I've Taken It"
        - action: "medicine_reminder_laura_mute_until_home" 
          title: "Mute Until I'm Home"