
# Ring Doorbell status updates (eg. wifi signal strength)
sensor:
  - platform: template
    sensors:
      ring_last_ding:
        value_template: '{% if states.sensor.front_door_last_ding.state not in ("unavailable", "unknown") %}{{ as_timestamp(states.sensor.front_door_last_ding.attributes["created_at"]) | timestamp_custom("%I:%M:%S%p, %a %d %B %Y", True) }}{% else %}unknown{% endif %}'
      ring_last_motion:
        value_template: '{% if states.sensor.front_door_last_motion.state not in ("unavailable", "unknown") %}{{ as_timestamp(states.sensor.front_door_last_motion.attributes["created_at"]) | timestamp_custom("%I:%M:%S%p, %a %d %B %Y", True) }}{% else %}unknown{% endif %}'

automation:
  - alias: Front Door - When Doorbell Is Rung After Dark, Turn On Light
    id: front_door_when_doorbell_is_rung_after_dark_turn_on_light
    trigger:
      platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
    condition:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id:
          - light.front_porch_light
          - light.entry_hall_lights