automation:
  - alias: Security Cameras - Turn On Infra-red When Turned Off
    id: security_cameras_turn_on_infra_red_when_turned_off
    trigger:
      - platform: state
        entity_id:
          - light.alfresco_infra_red_lights_in_night_mode
          - light.backyard_infra_red_lights_in_night_mode
        to: "off"
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.alfresco_infra_red_lights_in_night_mode
            - light.backyard_infra_red_lights_in_night_mode

  - alias: Security Cameras - Turn Off Living Room Camera Privacy Mode When Leaving House
    id: security_cameras_turn_off_living_room_camera_privacy_mode_when_leaving_house
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_home
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.living_room_camera_privacy
      - delay:
          seconds: 10
      - service: select.select_option
        data:
          option: Central Room
        target:
          entity_id: select.living_room_camera_move_to_preset

  - alias: Security Cameras - Turn On Living Room Camera Privacy Mode When Arriving Home
    id: security_cameras_turn_on_living_room_camera_privacy_mode_when_arriving_home
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_home
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.living_room_camera_privacy

  - alias: Security Cameras - Take Snapshot Of Back Garden Every Day
    id: security_cameras_take_snapshot_of_back_garden_every_day
    trigger:
      - platform: time
        at: "13:15:00"
    action:
      service: camera.snapshot
      target:
        entity_id: camera.backyard_camera
      data:
        filename: '/tmp/GardenTimeLapse/backyard/backyard_timelapse_{{ now().strftime("%Y%m%d") }}.jpg'

  - alias: Security Cameras - Take Snapshot Of Alfresco Every Day
    id: security_cameras_take_snapshot_of_alfresco_every_day
    trigger:
      - platform: time
        at: "13:15:00"
    action:
      service: camera.snapshot
      target:
        entity_id: camera.alfresco_camera
      data:
        filename: '/tmp/GardenTimeLapse/alfresco/alfresco_timelapse_{{ now().strftime("%Y%m%d") }}.jpg'

  - alias: Security Cameras - Take Snapshot Of Front Garden Every Day
    id: security_cameras_take_snapshot_of_front_garden_every_day
    trigger:
      - platform: time
        at: "13:15:00"
    action:
      service: camera.snapshot
      target:
        entity_id: camera.driveway_camera
      data:
        filename: '/tmp/GardenTimeLapse/front/frontyard_timelapse_{{ now().strftime("%Y%m%d") }}.jpg'

  - alias: Security Cameras - Save Photos of Dogs
    id: security_cameras_save_photos_of_dogs
    trigger:
      - platform: state
        entity_id: binary_sensor.driveway_dog_occupancy
        to: "on"
    action:
      service: camera.snapshot
      target:
        entity_id: camera.driveway_dog
      data:
        filename: "/tmp/DogPhotos/dog_{{ as_timestamp(now()) | int }}.jpg"

  - alias: Security Cameras - Notify Michael If Security Cameras Disconnect
    id: security_cameras_notify_michael_if_security_cameras_disconnect
    trigger:
      - platform: state
        entity_id:
          - camera.alfresco_camera
          - camera.backyard_camera
        to: "unavailable"
        for:
          minutes: 10
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "{{ trigger.entity_id }} has become unavailable."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_pixel_8_pro
        data:
          title: "Camera Connection Issue"
          message: "{{ chatgpt_response.text }}"
          data:
            group: Camera Unavailable
            notification_icon: "mdi:cctv-off"

  - alias: Security Cameras - Restart Swann DVR If Disconnected
    id: security_cameras_restart_swann_dvr_if_disconnected
    trigger:
      - platform: state
        entity_id:
          - camera.driveway_camera
          - camera.garage
          - camera.side_path_camera
        to: "unavailable"
        for:
          minutes: 10
    action:
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "{{ trigger.entity_id }} became unavailable so will be restarted."
          data:
            group: Camera Unavailable
            notification_icon: "mdi:cctv-off"
      - service: switch.turn_off
        target:
          entity_id: switch.swann_nvr_power
      - delay:
          seconds: 10
      - service: switch.turn_on
        target:
          entity_id: switch.swann_nvr_power

  - alias: Security Cameras - Sync Surveillance Station Home Mode With Alarm Status
    id: security_cameras_sync_surveillance_station_home_mode_with_alarm_status
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_home
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: 'binary_sensor.someone_home'
                state: 'off'
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.homenas_home_mode
          - conditions:
              - condition: state
                entity_id: 'binary_sensor.someone_home'
                state: 'on'
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.homenas_home_mode

  - alias: Security Cameras - Alert Michael When Car In Driveway
    id: security_cameras_alert_michael_when_car_in_driveway
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.driveway_only_car_occupancy
        to: "on"
      - platform: state
        entity_id: binary_sensor.driveway_only_motorcycle_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: cover.garage_door
        state: "closed"
    action:
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: "Someone has parked in the driveway..."
          data:
            group: "Driveway"
            image: /api/camera_proxy/camera.driveway_camera
            color: "red"
            ttl: 0
            priority: high
            clickAction: "entityId:camera.driveway_camera"
            vibrationPattern: "100, 1000, 100, 1000, 100, 1000, 100"
            channel: "Motion"
            notification_icon: "mdi:car-info"
            car_ui: true
            sticky: true
      #don't notify me again too quickly
      - delay:
          seconds: 30

  - alias: Security Cameras - Alert TV When Car In Driveway
    id: security_cameras_alert_tv_when_car_in_driveway
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.driveway_only_car_occupancy
        to: "on"
      - platform: state
        entity_id: binary_sensor.driveway_only_motorcycle_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: media_player.theatre_room_tv
        state: "on"
      - condition: state
        entity_id: cover.garage_door
        state: "closed"
    action:
      - service: notify.theatre_room_tv
        data:
          message: "There is a car in the driveway."
      #don't notify me again too quickly
      - delay:
          seconds: 30
