automation:
  - alias: Security Cameras - Turn Off Living Room Camera Privacy Mode When Leaving House
    id: security_cameras_turn_off_living_room_camera_privacy_mode_when_leaving_house
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_com
        from: 'disarmed'
        to: 'armed_away'
      - platform: state
        entity_id: alarm_control_panel.alarm_com
        from: 'disarmed'
        to: 'armed_home'
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.living_room_camera_privacy
      - delay:
          seconds: 10
      - service: select.select_option
        data:
          option: Central Room
        target:
          entity_id: select.living_room_camera_move_to_preset
 
  - alias: Security Cameras - Turn On Living Room Camera Privacy Mode When Arriving Home
    id: security_cameras_turn_on_living_room_camera_privacy_mode_when_arriving_home
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_com
        to: 'disarmed'
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.living_room_camera_privacy

  - alias: Security Cameras - Take Snapshot Of Back Garden Every Day
    id: security_cameras_take_snapshot_of_back_garden_every_day
    trigger:
      - platform: time
        at: "13:15:00"
    action:
      service: camera.snapshot
      target:
        entity_id: camera.backyard_camera
      data:
        filename: '/tmp/GardenTimeLapse/backyard_timelapse_{{ now().strftime("%Y%m%d") }}.jpg'

  - alias: Security Cameras - Notify Michael If Security Cameras Disconnect
    id: security_cameras_notify_michael_if_security_cameras_disconnect
    trigger:
      - platform: state
        entity_id:
          - camera.alfresco_camera
          - camera.backyard_camera
        to: 'unavailable'
        for:
          minutes: 10
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "{{ trigger.entity_id }} has become unavailable."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          message: "{{ chatgpt_response.text }}"
          data:
            group: Camera Unavailable

  - alias: Security Cameras - Sync Surveillance Station Home Mode With Alarm Status
    id: security_cameras_sync_surveillance_station_home_mode_with_alarm_status
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_com
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.alarm_com
              state: 
                - 'armed_home'
                - 'armed_away'
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.homenas_home_mode
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.alarm_com
              state: 'disarmed'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.homenas_home_mode