binary_sensor:
  - platform: rest
    resource: !secret sonarr_health_url
    headers:
      X-API-KEY: !secret sonarr_api_key
    method: GET
    name: Sonarr VPN Status
    device_class: connectivity
    value_template: "{{ 'error' not in (value_json | map(attribute='type') | join(', ')) }}"

rest_command:
  restart_server_vpn:
    url: !secret olivetin_api_url
    method: post
    payload: '{"actionName": "Restart VPN"}'
  sonarr_test_trackers:
    url: !secret sonarr_indexer_testall_url
    headers:
      X-API-KEY: !secret sonarr_api_key
    method: POST
  radarr_test_trackers:
    url: !secret radarr_indexer_testall_url
    headers:
      X-API-KEY: !secret radarr_api_key
    method: POST

sensor:  
  - platform: command_line
    name: NAS VPN Location
    command: ssh -i /config/ssh/id_rsa -o 'StrictHostKeyChecking=no' root@192.168.1.222 -p 222 'curl ipinfo.io'
    json_attributes:
      - city
      - region
      - country
    scan_interval: 30
    value_template: >
      {% if (value_json.ip | length) == 0 %}
        None
      {% else %}
        {{ value_json.ip }}
      {% endif %}

template:
  - sensor:
      - name: "NAS VPN Geographical Location"
        state: >
          {% if (states('sensor.nas_vpn_location') | length) == 0 %}
            None
          {% else %}
            {{  state_attr('sensor.nas_vpn_location', 'city') + ', ' 
            + state_attr('sensor.nas_vpn_location', 'region') + ', ' 
            + state_attr('sensor.nas_vpn_location', 'country') }}
          {% endif %}

#Change the Synology NAS/Theatre Room TV VPN Connection
shell_command:
  nas_vpn_disconnect: >
    ssh {{ nas_ssh_connection_string }} 'bash /volume1/NAS\ Config/VPN\ Scripts/disconnectfromvpn.sh'
  nas_vpn_connect_japan: >
    ssh {{ nas_ssh_connection_string }} 'bash /volume1/NAS\ Config/VPN\ Scripts/connecttovpn.sh NordVPN_Japan'
  nas_vpn_connect_uk: >
    ssh {{ nas_ssh_connection_string }} 'bash /volume1/NAS\ Config/VPN\ Scripts/connecttovpn.sh NordVPN_UK'
  nas_vpn_connect_usa: >
    ssh {{ nas_ssh_connection_string }} 'bash /volume1/NAS\ Config/VPN\ Scripts/connecttovpn.sh NordVPN_USA'

script:
  update_shelly_devices:
    alias: Update Shelly Devices
    sequence:
      - service: update.install
        target:
          entity_id:
            - update.shelly1pm_d8bfc019b9fe_firmware_update
            - update.shelly1pm_d8bfc019bfae_firmware_update
            - update.shelly1pm_d8bfc01a1071_firmware_update
            - update.shelly_em3_energy_monitor_firmware_update
            - update.bathroom_firmware_update
            - update.ensuite_toilet_light_and_fan_firmware_update
            - update.main_toilet_light_and_fan_firmware_update
            - update.office_ceiling_lights_firmware_update

  nas_vpn_connect:
    alias: Connect NAS VPN
    fields:
      vpnCountry:
        name: VPN & Country
        description: "The VPN and Country to connect to"
        selector:
          select:
            options:
              - None
              - NordVPN - Japan
              - NordVPN - UK
              - NordVPN - USA
    sequence:
      - choose:
          - conditions: >
              {{ vpnCountry == "None" }}
            sequence:
              - service: shell_command.nas_vpn_disconnect
                data:
                  nas_ssh_connection_string: !secret nas_ssh_connection_string
          - conditions: >
              {{ vpnCountry == "NordVPN - Japan" }}
            sequence:
              - service: shell_command.nas_vpn_connect_japan
                data:
                  nas_ssh_connection_string: !secret nas_ssh_connection_string
          - conditions: >
              {{ vpnCountry == "NordVPN - UK" }}
            sequence:
              - service: shell_command.nas_vpn_connect_uk
                data:
                  nas_ssh_connection_string: !secret nas_ssh_connection_string
          - conditions: >
              {{ vpnCountry == "NordVPN - USA" }}
            sequence:
              - service: shell_command.nas_vpn_connect_usa
                data:
                  nas_ssh_connection_string: !secret nas_ssh_connection_string
    mode: single

automation:
  #if server is getting too hot, send a push notification.
  - alias: Server Management - Notify If Server Temperature Too Hot
    id: server_management_notify_if_server_temperature_too_hot
    trigger:
      - platform: numeric_state
        entity_id: sensor.server_cupboard_temperature
        above: 40
      - platform: numeric_state
        entity_id: sensor.processor_temperature
        above: 90
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "The server is getting hot. Processor temperature: {{ states('sensor.processor_temperature') }}, cupboard temperature: {{ states('sensor.server_cupboard_temperature') }}"
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          title: "WARNING: The server is getting hot!"
          message: "{{ chatgpt_response.text }}"
          notification_icon: "mdi:thermometer-alert"

  - alias: Server Management - Restart VPN if Sonarr disconnected for too long
    id: server_management_restart_vpn_if_sonarr_disconnected_for_too_long
    trigger:
      - platform: state
        entity_id: binary_sensor.sonarr_vpn_status
        to: "off"
        for:
          minutes: 20
    action:
      - service: script.chatgpt_reword_message
        data:
          prompt: "'Sonarr' had lost conenction to the VPN."
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          title: "The VPN was automatically restarted"
          message: "{{ chatgpt_response.text }}"
          data:
            group: "VPN_Restart"
            notification_icon: "mdi:earth"
      - service: rest_command.restart_server_vpn
      - delay:
          minutes: 5
      - service: rest_command.sonarr_test_trackers
      - service: rest_command.radarr_test_trackers
      - delay:
          minutes: 5
      - condition: state
        entity_id: binary_sensor.sonarr_vpn_status
        state: "off"
      - service: script.chatgpt_reword_message
        data:
          prompt: "'Sonarr' still has no access to the VPN"
        response_variable: "chatgpt_response"
      - service: notify.mobile_app_michael_s_galaxy_s10
        data:
          title: "The VPN restart was not successful"
          message: "{{ chatgpt_response.text }}"
          data:
            group: "VPN_Restart"
            notification_icon: "mdi:earth-off"
