light:
  - platform: switch
    name: Front Porch Light
    entity_id: switch.front_porch_light
  - platform: switch
    name: Kitchen Ceiling Light
    entity_id: switch.kitchen_ceiling_light
  - platform: switch
    name: Ensuite Light
    entity_id: switch.ensuite_light