# Todoist To-Do and Shopping Lists 
calendar:
  - platform: todoist
    token: !secret todoist_api_key

var:
  show_shopping_list_house_stuff:
    friendly_name: Show House Stuff Shopping List
    initial_value: False

script:
  toggle_var_show_shopping_list_house_stuff:
    sequence:
      - service: var.set
        data:
            entity_id:
            - var.show_shopping_list_house_stuff
            value_template: >-
              {% if is_state('var.show_shopping_list_house_stuff', 'True') %}
                False
              {% else %}
                True 
              {% endif %}