spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

script:
  spotify_swipe_right_on_all_rooms:
    sequence:
      service: spotcast.start
      data:
        entity_id: media_player.all_rooms
        uri: spotify:playlist:57T6RAcRkqB5vPeqojKUzs
        shuffle: true
        random_song: true

  spotify_swipe_left_on_all_rooms:
    sequence:
      service: spotcast.start
      data:
        entity_id: media_player.all_rooms
        uri: spotify:playlist:5UiNzaro2CD4e6G5vEra4D
        shuffle: true
        random_song: true

automation:
  #When arriving home, transfer any spotify music playing from my phone to the house
  - alias: Spotify - Transfer music to All Rooms when arriving home
    id: spotify_transfer_music_to_all_rooms_when_arriving_home
    trigger:
      - platform: zone
        entity_id: person.michael
        zone: zone.home
        event: enter
    condition:
      - alias: "Spotify is playing"
        condition: state
        entity_id: media_player.spotify_micker_t
        state: "playing"
      - alias: "Laura is not home"
        condition: zone
        entity_id: person.laura
        zone: zone.home
      # Do not run during Christmas as the Christmas music automation overrides it
      - alias: "Christmas automations aren't active"
        condition: state
        entity_id: input_boolean.enable_christmas_automations
        state: "false"
    action:
      - alias: "Wait until garage door opens"
        wait_for_trigger:
          - platform: state
            entity_id: cover.garage_door
            to: "opening"
      - service: spotcast.start
        data:
          device_name: All Rooms
