var:
  show_shopping_list_house_stuff:
    friendly_name: Show House Stuff Shopping List
    initial_value: False

script:
  toggle_var_show_shopping_list_house_stuff:
    sequence:
      - service: var.set
        data:
            entity_id:
            - var.show_shopping_list_house_stuff
            value_template: >-
              {% if is_state('var.show_shopping_list_house_stuff', 'True') %}
                False
              {% else %}
                True 
              {% endif %}

automation:
  - alias: Todo List - Add Item To Todo List Via Voice
    id: todolist_add_item_to_todo_list_via_voice
    trigger:
      - platform: conversation
        command:
          - "Add {todotask} to my (to-do|todo|to do|To Do|To-Do|ToDo) list"
          - "Remind me to {todotask}"
    action:
      - service: todoist.new_task
        data:
          project: Inbox
          due_date_string: today
          content: "{{ trigger.slots.todotask }}"

  - alias: Todo List - Add Item To Shopping List Via Voice
    id: todolist_add_item_to_shopping_list_via_voice
    trigger:
      - platform: conversation
        command:
          - "Add {fooditem} to (my|the) shopping list"
          - "Add {fooditem}"
    action:
      - service: todoist.new_task
        data:
          project: Groceries List
          content: "{{ trigger.slots.fooditem }}"
