automation:
  - alias: Toilets - Turn Off Ensuite Toilet Light After Thirty Min
    id: toilets_turn_off_ensuite_toilet_light_after_thirty_min
    trigger:
      - platform: state
        entity_id: light.ensuite_toilet_light_and_fan
        to: 'on'
        for:
          minutes: 30
    action:
      - service: switch.turn_off
        data:
          entity_id: light.ensuite_toilet_light_and_fan

  - alias: Toilets - Turn Off Main Toilet Light After Thirty Min
    id: toilets_turn_off_main_toilet_light_after_thirty_min
    trigger:
      - platform: state
        entity_id: light.main_toilet_light_and_fan
        to: 'on'
        for:
          minutes: 30
    action:
      - service: switch.turn_off
        data:
          entity_id: light.main_toilet_light_and_fan