script:
  turn_off_all_lights:
    sequence:
      - service: light.turn_off
        data_template: 
          entity_id: "{{ states.light | map(attribute='entity_id') | list | join(', ') }}"
  turn_off_whole_house:
    sequence:
      - service: script.turn_off_all_lights
      - service: script.aircon_turn_off_all_zones
      - service: switch.turn_off
        entity_id: switch.aircon_on_off
      - service: media_player.turn_off #tv & speakers
        entity_id:
          - media_player.theatre_room_tv 
          - media_player.all_rooms
      - service: cover.close_cover
        entity_id: cover.theatre_blinds
