light:
    - platform: switch
      name: Alfresco Ceiling Lights
      entity_id: switch.alfresco_ceiling_lights
    - platform: switch
      name: Garden Flood Lights
      entity_id: switch.garden_flood_lights