views:
  - panel: true
    badges: []
    cards:
      - type: grid
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.garage_camera
            name: Garage
            camera_image: camera.garage_camera
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.side_path
            name: Side Path
            camera_image: camera.side_path
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.living_room_camera_sd
            name: Living Room
            camera_image: camera.living_room_camera_hd
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.alfresco_camera
            name: Alfresco
            camera_image: camera.alfresco_camera
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.backyard_camera
            name: Backyard
            camera_image: camera.backyard_camera
          - square: false
            columns: 3
            type: grid
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: switch.living_room_camera_privacy
                show_state: true
                name: Privacy Mode
                icon: mdi:eye-outline
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: select.select_option
                  data:
                    option: Central Room
                  target:
                    entity_id: select.living_room_camera_move_to_preset
                name: Central Room
                icon: mdi:camera-control
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: select.select_option
                  data:
                    option: Kitchen
                  target:
                    entity_id: select.living_room_camera_move_to_preset
                name: Kitchen
                icon: mdi:camera-control
              - type: glance
                entities:
                  - entity: binary_sensor.dog_door
                    icon: mdi:dog-side
                    name: Dog Door
                    show_last_changed: true
          - type: picture-entity
            entity: camera.last_front_door_motion
            name: Last Motion
            camera_image: camera.last_front_door_motion
            camera_view: live
            show_name: true
            show_state: false
            columns: 4
          - type: picture-entity
            entity: camera.ender_3_s1
            camera_image: camera.ender_3_s1
            camera_view: live
            show_state: false
            columns: 4
        columns: 3
        square: false
title: Security Cameras
