views:
  - panel: true
    badges: []
    cards:
      - type: grid
        cards:
          - camera_view: auto
            type: picture-glance
            title: Garage
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities:
              - entity: light.garage_light
            camera_image: camera.garage_camera
            entity: camera.garage_camera
          - camera_view: auto
            type: picture-glance
            title: Side Path
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities:
              - entity: light.washing_line_lights
            camera_image: camera.side_path
            entity: camera.side_path
          - camera_view: auto
            type: picture-glance
            title: Doorbell
            image: camera.doorbell_sub
            entities:
              - entity: light.front_porch_light
            camera_image: camera.doorbell_sub
            entity: camera.doorbell_main
          - camera_view: auto
            type: picture-glance
            title: Living Room
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities:
              - entity: switch.living_room_camera_privacy
            camera_image: camera.living_room_camera_hd
            entity: camera.living_room_camera_hd
          - camera_view: auto
            type: picture-glance
            title: Alfresco
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities:
              - entity: light.alfresco_ceiling_lights
              - entity: light.alfresco_fairy_lights
            camera_image: camera.alfresco_camera
            entity: camera.alfresco_camera
          - camera_view: auto
            type: picture-glance
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities:
              - entity: light.garden_flood_lights
            title: Backyard
            camera_image: camera.backyard_camera
            entity: camera.backyard_camera
          - square: false
            columns: 3
            type: grid
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: select.select_option
                  data:
                    option: Central Room
                  target:
                    entity_id: select.living_room_camera_move_to_preset
                name: Centered
                icon: mdi:camera-control
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: select.select_option
                  data:
                    option: Kitchen
                  target:
                    entity_id: select.living_room_camera_move_to_preset
                name: Kitchen
                icon: mdi:camera-control
              - type: glance
                entities:
                  - entity: binary_sensor.dog_door
                    icon: mdi:dog-side
                    name: Dog Door
                    show_last_changed: true
          - camera_view: auto
            type: picture-glance
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities:
              - entity: light.office_lamp
            title: Ender 3 S1
            camera_image: camera.ender_3_s1
            entity: camera.ender_3_s1
        columns: 3
        square: false
title: Security Cameras
