views:
  - panel: true
    badges: []
    cards:
      - type: grid
        cards:
          - type: picture-entity
            entity: camera.garage_camera
            name: Garage
            camera_image: camera.garage_camera
            camera_view: live
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.side_path
            name: Side Path
            camera_image: camera.side_path
            camera_view: live
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.living_room_camera_hd
            name: Living Room
            camera_image: camera.living_room_camera_hd
            camera_view: live
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.alfresco_camera
            name: Alfresco
            camera_image: camera.alfresco_camera
            camera_view: live
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.backyard_camera
            name: Backyard
            camera_image: camera.backyard_camera
            camera_view: live
            show_name: false
            show_state: false
          - type: grid
            cards:
              - type: button
                tap_action:
                  action: toggle
                entity: switch.living_room_camera_privacy_mode
                show_state: true
                name: Privacy Mode
              - type: button
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    preset: Dog Door
                  target:
                    device_id: 3cf71e0c142a900622f37d4d238030ce
                name: Dog Door
                icon: mdi:camera-control
              - type: button
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    preset: Couches
                  target:
                    device_id: 3cf71e0c142a900622f37d4d238030ce
                name: Couches
                icon: mdi:camera-control
              - type: button
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    preset: Dining Room
                  target:
                    device_id: 3cf71e0c142a900622f37d4d238030ce
                name: Dining Room
                icon: mdi:camera-control
              - type: button
                tap_action:
                  action: call-service
                  service: tapo_control.ptz
                  service_data:
                    preset: Dog Bed
                  target:
                    device_id: 3cf71e0c142a900622f37d4d238030ce
                name: Dog Bed
                icon: mdi:camera-control
              - type: glance
                entities:
                  - entity: binary_sensor.dog_door
                    icon: mdi:dog-side
                    name: Dog Door
                    show_last_changed: true
          - type: picture-entity
            entity: camera.last_front_door_motion
            name: Last Motion
            camera_image: camera.last_front_door_motion
            camera_view: live
            show_name: true
            show_state: false
            columns: 4
        columns: 3
        square: false
title: Security Cameras
