title: Cooking
views:
  - title: iGrill Control
    badges: []
    cards:
      - type: custom:stack-in-card
        title: iGrill Probe Temperatures
        cards:
          - type: custom:dual-gauge-card
            title: Probe 1
            min: 0
            max: 100
            outer:
              entity: sensor.igrill_probe_1
              label: Current
              unit: °C
              colors:
                - color: var(--label-badge-white)
                  value: unavailable
                - color: var(--label-badge-red)
                  value: 0
            inner:
              entity: input_number.igrill_probe_1_target_temp
              label: Target
              unit: °C
              colors:
                - color: var(--label-badge-blue)
          - type: custom:dual-gauge-card
            title: Probe 2
            min: 0
            max: 100
            outer:
              entity: sensor.igrill_probe_2
              label: Current
              unit: °C
              colors:
                - color: var(--label-badge-white)
                  value: unavailable
                - color: var(--label-badge-yellow)
                  value: 0
            inner:
              entity: input_number.igrill_probe_2_target_temp
              label: Target
              unit: °C
              colors:
                - color: var(--label-badge-blue)
          - type: custom:dual-gauge-card
            title: Probe 3
            min: 0
            max: 100
            outer:
              entity: sensor.igrill_probe_3
              label: Current
              unit: °C
              colors:
                - color: var(--label-badge-white)
                  value: unavailable
                - color: var(--label-badge-green)
                  value: 0
            inner:
              entity: input_number.igrill_probe_3_target_temp
              label: Target
              unit: °C
              colors:
                - color: var(--label-badge-blue)
          - type: custom:mini-graph-card
            name: Ambient Probe
            hours_to_show: 0.5
            points_per_hour: 60
            entities:
              - entity: sensor.igrill_probe_4
                name: Ambient Probe
                color: var(--label-badge-blue)
              - entity: input_number.igrill_ambient_alert_low_temp
                name: Minimum Target
                color: var(--label-badge-green)
              - entity: input_number.igrill_ambient_alert_high_temp
                name: Maximum Target
                color: var(--label-badge-red)
            align_state: center
            show:
              fill: false
      - type: history-graph
        entities:
          - entity: sensor.igrill_probe_1
          - entity: sensor.igrill_probe_2
          - entity: sensor.igrill_probe_3
          - entity: sensor.igrill_probe_4
            name: iGrill Ambient
        refresh_interval: 0
        title: iGrill Probe Temperature History
        hours_to_show: 8
      - type: custom:stack-in-card
        title: iGrill Target Temperature Presets
        cards:
          - type: entities
            entities:
              - entity: input_select.igrill_presets_probe
                name: 'Probe to set:'
          - type: grid
            cards:
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: beef
                    doneness: rare
                name: Rare
                icon: mdi:cow
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: beef
                    doneness: medium rare
                name: Medium Rare
                icon: mdi:cow
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: beef
                    doneness: medium
                name: Medium
                icon: mdi:cow
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: lamb
                    doneness: rare
                name: Rare
                icon: mdi:sheep
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: lamb
                    doneness: medium rare
                name: Medium Rare
                icon: mdi:sheep
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: pork
                name: Medium
                icon: mdi:pig
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: chicken
                name: Well Done
                icon: mdi:turkey
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: duck
                name: Well Done
                icon: mdi:duck
              - type: button
                tap_action:
                  action: call-service
                  service: script.igrill_set_alert_temperature_from_preset
                  service_data:
                    meat: fish
                name: Medium Well
                icon: mdi:fish
            square: true
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: script.igrill_cast_dashboard_to_living_room_tv
          service_data: {}
          target: {}
        name: Show Dashboard On TV
        icon: mdi:television-classic
      - type: entities
        show_header_toggle: false
        title: iGrill Temperature Alerts
        entities:
          - entity: input_number.igrill_ambient_alert_low_temp
          - entity: input_number.igrill_ambient_alert_high_temp
          - entity: sensor.igrill_ambient_alert_temp
          - entity: input_number.igrill_probe_1_target_temp
          - entity: sensor.igrill_target_alert_temp_probe_1
          - entity: input_number.igrill_probe_2_target_temp
          - entity: sensor.igrill_target_alert_temp_probe_2
          - entity: input_number.igrill_probe_3_target_temp
          - entity: sensor.igrill_target_alert_temp_probe_3
          - entity: automation.igrill_google_assistant_notify_when_food_is_ready
            name: Google Home Alerts
            icon: mdi:google-home
        state_color: false
      - type: glance
        entities:
          - entity: binary_sensor.raspberry_pi_bluetooth_hub
            name: Bluetooth Hub
          - entity: switch.rpi_bluetooth_hub_smart_plug_power
            name: Hub Power Switch
          - entity: sensor.igrill_battery
        title: Technical Info
        state_color: true
      - type: entities
        entities:
          - entity: sensor.igrill_probe_1
            secondary_info: last-updated
            name: Probe 1
          - entity: sensor.igrill_probe_2
            secondary_info: last-updated
            name: Probe 2
          - entity: sensor.igrill_probe_3
            name: Probe 3
            secondary_info: last-updated
          - entity: sensor.igrill_probe_4
            name: Ambient Probe
            secondary_info: last-updated
          - entity: sensor.igrill_battery
            secondary_info: last-updated
        title: Latest iGrill Updates
      - type: weather-forecast
        entity: weather.treeby_house
        show_forecast: false
        name: Treeby
        secondary_info_attribute: wind_speed
  - title: iGrill Dashboard
    path: igrill-dashboard
    panel: true
    badges: []
    cards:
      - square: false
        columns: 3
        type: grid
        cards:
          - type: custom:dual-gauge-card
            title: Probe 1
            min: 0
            max: 100
            outer:
              entity: sensor.igrill_probe_1
              label: Current
              unit: °C
              colors:
                - color: var(--label-badge-white)
                  value: unavailable
                - color: var(--label-badge-red)
                  value: 0
            inner:
              entity: input_number.igrill_probe_1_target_temp
              label: Target
              unit: °C
              colors:
                - color: var(--label-badge-blue)
          - type: custom:dual-gauge-card
            title: Probe 2
            min: 0
            max: 100
            outer:
              entity: sensor.igrill_probe_2
              label: Current
              unit: °C
              colors:
                - color: var(--label-badge-white)
                  value: unavailable
                - color: var(--label-badge-yellow)
                  value: 0
            inner:
              entity: input_number.igrill_probe_2_target_temp
              label: Target
              unit: °C
              colors:
                - color: var(--label-badge-blue)
          - type: custom:dual-gauge-card
            title: Probe 3
            min: 0
            max: 100
            outer:
              entity: sensor.igrill_probe_3
              label: Current
              unit: °C
              colors:
                - color: var(--label-badge-white)
                  value: unavailable
                - color: var(--label-badge-green)
                  value: 0
            inner:
              entity: input_number.igrill_probe_3_target_temp
              label: Target
              unit: °C
              colors:
                - color: var(--label-badge-blue)
          - type: custom:mini-graph-card
            name: Ambient Probe
            hours_to_show: 0.5
            points_per_hour: 60
            line_width: 2
            height: 50
            entities:
              - entity: sensor.igrill_probe_4
                name: Ambient Probe
                color: var(--label-badge-blue)
              - entity: input_number.igrill_ambient_alert_low_temp
                name: Minimum Target
                color: var(--label-badge-green)
              - entity: input_number.igrill_ambient_alert_high_temp
                name: Maximum Target
                color: var(--label-badge-red)
            align_state: center
            show:
              fill: false
              points: false
              legend: true
          - type: history-graph
            entities:
              - entity: sensor.igrill_probe_1
              - entity: sensor.igrill_probe_2
              - entity: sensor.igrill_probe_3
              - entity: sensor.igrill_probe_4
                name: iGrill Ambient
            refresh_interval: 0
            hours_to_show: 8
            title: Last 8 Hours
          - type: picture-entity
            entity: camera.alfresco_camera
            name: Garage
            camera_image: camera.alfresco_camera
            camera_view: live
            show_name: false
            show_state: false
