homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Customization file
  customize: !include customize.yaml
  # Package config: https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages 

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Import themes from the themes directory managed by HACS
frontend:
  themes: !include_dir_merge_named themes

#Include other configuration files
#automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
#switch: !include switches.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:
ssdp:
zeroconf:

# Todoist To-Do and Shopping Lists 
calendar:
 - platform: todoist
   token: !secret todoist_api_key
    
# Elastic search output
elastic:
  url: http://192.168.1.111:9200
  exclude:
    entities: ['sensor.es_cluster_health', 'sensor.es_publish_queue', 'sun.sun']

hue:
  bridges:
    - host: !secret hue_bridge_ip_address
      allow_unreachable: true
      allow_hue_groups: true

# Text to speech
tts:
  - platform: google_translate

# Aeotec Z-Wave Stick
zwave:
  usb_path: /zwaveusbstick
  device_config: !include zwave_device_config.yaml
