homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Customization file
  customize: !include customize.yaml
  # Package config: https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages 
  # URLs to access Home Assistant
  external_url: !secret home_assistant_external_url
  internal_url: !secret home_assistant_internal_url

  currency: AUD

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Import themes from the themes directory managed by HACS
frontend:
  themes: !include_dir_merge_named themes

#Include other configuration files
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

# Discover some devices automatically
discovery:
ssdp:
zeroconf:
    
influxdb:
  host: !secret influx_db_ip_address
  port: !secret influx_db_port
  database: home_assistant
  max_retries: 3
  default_measurement: state
  exclude:
    entities:
        - sensor.es_cluster_health
        - sensor.es_publish_queue
        - sun.sun
  tags_attributes:
    - friendly_name

# Aeotec Z-Wave Stick
zwave:
  usb_path: /zwaveusbstick
  device_config: !include zwave_device_config.yaml
