media_players:
  name: All Media Players
  entities:
    - media_player.kitchen_google_home_hub
    - media_player.living_room_chromecast
    - media_player.master_bedroom_speaker
    - media_player.office_google_home
    - media_player.office_pc_speakers
    - media_player.theatre_room_chromecast
    - media_player.theatre_room_google_home
    - media_player.theatre_room_tv
    
speakers:
  name: Speakers
  entities: 
    - media_player.kitchen_google_home_hub
    - media_player.living_room_chromecast
    - media_player.master_bedroom_speaker
    - media_player.office_google_home
    - media_player.office_pc_speakers
    
televisions:
  name: TVs
  entities:
    - media_player.theatre_room_chromecast
    - media_player.theatre_room_google_home
    - media_player.theatre_room_tv