light.fibaro_system_fgd212_dimmer_2_level_3:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level_5:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level_8:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level_7:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level_6:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level_11:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level_2:
  ignored: true
  polling_intensity: 0
light.fibaro_system_fgd212_dimmer_2_level_10:
  ignored: true
  polling_intensity: 0
sensor.aeon_labs_zw100_multisensor_6_ultraviolet_2:
  ignored: false
  polling_intensity: 0
sensor.laundry_multisensor_6_sourcenodeid:
  ignored: true
  polling_intensity: 0
binary_sensor.laundry_multisensor_6_sensor:
  ignored: true
  polling_intensity: 0
sensor.laundry_multisensor_6_temperature:
  ignored: false
  polling_intensity: 0
