name: Check HA Release Compatibility
on: repository_dispatch
jobs:
  check-ha-config:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Branch: ${{ github.event.client_payload.branch }}"'
      - run: 'echo "Release Type: ${{ github.event.client_payload.release_type }}"'
      - run: 'echo "Release Version: ${{ github.event.client_payload.version }}"'

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1   
        with:
          python-version: '3.7.x'

      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libudev-dev && sudo apt-get install -y python3-bs4
          
      - name: Install Home Assistant Stable
        if: github.event.client_payload.branch == 'stable'
        run: pip3 install homeassistant
      
      - name: Install Home Assistant RC
        if: github.event.client_payload.branch == 'rc'
        run: pip3 install --pre homeassistant

      - name: Install Home Assistant Dev
        if: github.event.client_payload.branch == 'dev'
        run: pip3 install git+git://github.com/home-assistant/home-assistant.git@dev

      - name: Check Config
        run: |
          mv ./config/secrets.yaml.template ./config/secrets.yaml
          hass -c ./config --script check_config -i -f
          
  upgrade_hass:
    runs-on: ubuntu-latest
    needs: check-ha-config
    # Only run if config check succeeds
    if: github.event.client_payload.branch == 'stable'
    steps:
      - name: Upgrade HASS Minor Release
        # Add this secret to your Github repo's secrets in its settings.
        run: curl -X POST ${{ secrets.HASS_WEBHOOK }}
        # Only run if passed release_type = minor
        if: github.event.client_payload.release_type == 'minor'
